### ISSUE TITLE
Accordian (FAQ)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#102]
![Merative-Accordian](https://user-images.githubusercontent.com/7074782/213327824-8f77ed90-a728-4076-b500-43ef0c837c48.png)

Source: https://www.merative.com/clinical-development

Figma: https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=1459%3A19121&t=7U01EXpJQl5A7BdK-0

**Comment by VladimirZaets** [comment]
@amol-anand I already made some prototype, but I have batch of questions related to design that are not covered in figma.

- What behavior should be on item hover?
- How the item separator line should looks like for white/bone style (in figma covered just case with purple design, but it doesn't suitable for white/bone.
- The styles of separator line are changing when item is open, but what should be with the first item that doesn't have top separator?
