### ISSUE TITLE
People List (Leadership Team)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#103]
![Merative-Leadership-Team](https://user-images.githubusercontent.com/7074782/213328941-0f1f1ed7-887d-4871-9f4e-274e5808fffc.png)

List with Image, Title, sub-title

Source: https://www.merative.com/leadership

**Comment by VladimirZaets** [comment]
@jfait Hi, I already working on this issue, I cannot assign myself (doesn't have permissions)

**Comment by jfait** [comment]
I grabbed it as it was unassigned. 
@VladimirZaets or @amol-anand can you suggest another "simple" page for me ?
