### ISSUE TITLE
Ana and Garrett Design QA

### ISSUE THREAD

**Issue by gboxmerative** [hlxsites/merative#107]
### Blog Franklin Design QA v1 

For reference: 
Dev on left / Design on the right 

Figma Design: 
https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=474%3A242&t=bPP7eXFPCMyt4KSj-4 

Dev: https://main--merative--hlxsites.hlx.page/blog 
Ana- https://www.merative.com/blog 

### Desktop: 1440 

A. Headspace 
Spacing above Merative blog title should be 96px, its 32px now.  &check; (fixed as part of #66 )
Overall grid spacing – 156px from left and right needed, right now it's 149px &check;
Spacing left navigation and right featured article should be 48px, its 56px now &check; 

B. Left Navigation 
Extra Spacing of 16px above Clinical development support and categories &check; 
Spacing after Social program management should be 48px, its 24px now &check; 
Extra Spacing of 16px above Employer. &check; 
Extra 16px spacing above Real- World Evidence &check; 
The color of the checkbox is blue; it should be neutral carbon &check; 
The dimension of the checkbox is 16.5px, it should be 24px. &check; 
Spacing above showing results for should be 48px, right now it's 16px &check; 
The spacing between the pills should be 8px, right now its 4px. &check; 

Ana - A. 1440  
Side bar nav: reduce the space below Merative Blog to 32px  &check;
Update the size of the checkboxes to reflect the style: https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=474%3A522&t=RFgOQgBcmhLKLBck-1  &check;
Top feature card copy area, left gutter, increase space to 48px &check;
Top feature card copy area, center align copy in the space, so shift it down.  (Pending, need more info)
Card tags, increase font size to match design &check;
On all cards, remove author titles. Only have first, last name and read time &check; (now will be fixed as part of #109)
Top main nav area: Logo shifts down when you click on it and return to the Merative homepage &check; : (expected behavior as headers are different for merative.com and blog and might not be pixel perfect but in phase2 this should be resolved once we move over the complete site)
Top main nav area: Resources missing on state with underline &check;
Full card should be clickable. Currently only the article title is clickable.  &check;

C. Featured Article
Featured article image size should be 396x346px. &check; (current featured article content goes beyond 346px so the image adjusts accordingly)
The spacing between the title and top edge of card should be 64px. &check; 
The spacing on left (with the image), right and bottom edge from the text should be 48px. &check; 
The spacing between Article title and body copy should be 8px, right now its 16px. &check; 
The spacing between body copy and authors name should be 48px. &check; 

D. Blog Cards
Article image size should be 396x264px. &check; 
The spacing between the title and top and all edges of card should be 32px. &check; 
The spacing on left (with the image), right and bottom edge from the text should be 32px. &check; 
The spacing between Article title and body copy should be 8px, right now its 16px. &check; 
The spacing between body copy and authors name should be 24px. &check; 
Shadow on hover state of card is wrong. &check; 

Ana - C. 1440
Below Title and body, update style for “Showing results for”  &check; 
Missing ‘Clear’ all’ link off to the right of that &check; 
Topic pills needs space to the right of the ‘x’ &check; 
Selected checkmark style needs to match design &check; 
Missing topic 5th one down in the list &check; 
Wrong load more CTA is used (Dimensions are wrong). &check; 
The spacing below the CTA should be 160px. &check; 

Ana - B. 1440
Load more CTA should say “Load more” lower case “more”  &check; 
Footer: logo size needs to increase &check; 
Footer, contact and follow us icons needs to match design, they look like they’re smaller and not centered in the circles. &check; 
Footer: reduce spacing above the contact and follow us icons &check; 
Terms of use bottom links: increase space below line rule to 32px &check; 
Terms of use line rule: update color to match design &check; 
Remove purple line rule under Cookie preferences &check; 
Purple back to top button needs to match what we have site wide. It looks smaller  &check; 
Missing thumbnail image when there isn’t an image included with the card &check; 

Ana - D. 1440
Category page- add space after last card... see homepage bug &check; 

### Tablet: 760

A. Merative Blog Header
Top navigation bar – Padding on left and right is wrong. It’s 96 right now, should be 36. &check; 
Merative logo size is different. Should be 45px in height &check; 
Extra space of 32px is added above the title merative blog. It should be 64 only. &check; 
The title of the merative blog and bodycopy is on sand background.  (**Pending**)
The spacing between the body copy and the edge of the sand background is 48px.  (**Pending**)
From the sand background the filters have spacing of 32px.  (**Pending**)
The spacing between the filters and the feature article should be 32px. &check; 
Article image size should be 336x294. &check; 
The spacing between the body opy and the author in the feature article should be 48px. &check; 
The title font of feature article should be 18px Alliance no.1 light. &check; 
The author font should also be Alliance no.1 light 12px. &check; 
Please remove ‘Showing results for” and the pills below it. &check; 
Filters gradient pipe should be 4x24px  &check; 
Topic pills over top imagery- font size looks too small, please adjust &check; 

B. Article Cards
Extra padding of 16px is seen on left side. The padding should 36px from both sides. &check; 
The spacing between the card article title and its body copy should be 8px. It’s 16px now. &check; 
The space between body copy and the author's name should be 24px. &check; 
The author font should be Alliance no.1 light not regular. &check; 
Same feedback as desktop regarding full cards being clickable. &check; 

C. Load More
The spacing below the CTA should be 64px and not 160px. &check; 
If no load more, we should have 64px of space below the last card and above the footer &check; 

D. Article Cards
Reduce space below filters &check;
Missing top background color  (**Pending**, already reported above)
Intro body below title increase size to match design &check;

E. Footer
Same feedback around the spacing above the footer area and after the last card. &check;
Same feedback regarding the footer layout (fixed as part of issue 114 )

F. Category Selector
Filter font should be Mobile/heading/h4 - 18px medium and not light. &check; 
Padding of the entire filter from left should be 36px and not 16px. &check; 
The cross icon should be of 20px size. &check; 
The cross icon spacing from the right should be 24px.  &check; 
The spacing between filter text and Merative blog container should be 32px and then an 8px space is added above merative 
blog text. &check; 
The spacing below merative blog text and divider rule should be 24px. &check; 
The spacing above categories (and divider rule) should be 16px and below should be 24px. &check; 
The spacing between all the categories should be 16px. &check; 
Same follows as above (Point 7 and 8) for the audience and topic categories.  &check; 
Can we add some animation to the filter bar? It should slide open from the side. (**Pending**)
Please remove bar under Care Delivery, it’s not needed &check; 

G. Scrolling
Missing sticky Filters band. When a user scrolls the filters should be sticky at the top. &check; 

H. Category Band
Please double check type size of Categories and audiences super titles- they look smaller in the design &check; (changed to 11px )
Please double check weight of Apply and Reset, they look too light Please check the size and weight of the box and arrow for the checkboxes. Looks too big.  &check; 
Filters type weight looks too light, and arrow off to the right to close the panel as well. &check;
Same feedback for mobile &check;

I. Category Checkbox
Once scrolling the filters is sticky, but the drop shadow looks too light. Please reference design for colors. &check; 
Same feedback for mobile 

### Tablet: Article 768

Top nav merative logo and hamburger padding is incorrect. &check;
Breadcrumb padding on left is wrong. It should be 36px as our grid padding. &check;
The article hierarchy is wrong. &check;
After breadcrumb Article title should come > Tags > Article image > Author name > Share links > Reading progress. &check; (this was already discussed in phase 1. Can review this again if need be )
Article image size should be 696x468. &check;
No padding seen on right hand side.  &check;
Spacing above related article should be 64px.  &check;
Spacing below related article should be 48px. &check;
The color of card should be white. &check;
The image size inside the card should be 336x224. &check;
The spacing of title and bodycopy inside the card should be 8px. &check;
The spacing from bodycopy to author name should be 24px. &check;
Author font should be light. &check;
Leadgen grid is wrong. &check;
Ready for consultation font should be Mobile/heading/h2 32px sorce serif pro light. &check;
Bodycopy should be 16px alliance no.1 light  &check;
Spacing from bodycopy to CTA should be 32px. &check;

### Mobile: 375

Grid issue on mobile 
Need to fix it and then can be reviewed. 
Grid on mobile is wrong. 24px padding should be on both sides. &check;
Content is overlapping over the grid on right. &check; 
The spacing above and below of authors name should be 32px. &check;
Space above related article text should be 64px and below it should be 48px. &check;

B. Cards
Cards background should be white.  &check;
The spacing between Title and bodycopy should be 8px. &check;

C. CTA
Ready for consultation font should be 32px source serif pro light. &check;
Bodycopy font should be 16px Alliance no.1 light. &check;
The spacing between title and bodycopy should be 16px. &check;
Spacing above CTA should be 32px. &check;
The spacing between the bodycopy and the author's name should be 24px. &check;

### Hope this is the right link. 

Merative logo getting cut from the top. &check;
Cards in related article should have a white bg. Right now only on hover state it shows a white bg. &check;
Huge vertical side rainbow bar is seen &check;
Top nav bar is missing on tablet and mobile. &check;
Extra padding on right on mobile. 24px padding should be on both sides on mobile. &check;
The spacing on both left and right side should be 24px inside the card for text. &check;
The spacing between title and bodycopy should be 8px. &check;
The spacing between bodycopy and author’s name should be 24px. &check;
The authors font should be 12px Alliance no.1 light &check;

B. Filters Mobile
Logo in top nav bar needs to be smaller &check;
Reduce space above Merative Blog title &check;
Add missing background color &check;
Remove Showing results for and pills below it &check;
Feature story image needs to be taller (**Pending**, need to review again)
Topic pills on all card text needs to be larger &check;
On mobile when clicking on the logo to go back to the homepage the logo and main nav bar shift up, probably because of the larger logo size. &check; (as merative home and merative blog headers are different for now)
When no filters are selected there shouldn’t be any number to the right. I see a (0). (**Pending**)
Same feedback for the Category pages 

C. Footer
 Reduce space above Load more CTA. &check;
Lower case ‘more’ in the CTA &check;
Social media buttons are not in the correct position and they look larger and icons not centered. &check;
Remove purple underline on Cookie preferences link &check;
Same feedback on all category pages 
The spacing below the load more CTA should be 64px. &check;

D. Category Menu
The dropdown arrows in hamburger menu should align with the cancel button on top...i.e dropdown arrows should have a padding of 24px from the right. &check;

E. Links
Extra spacing can be seen before the blue links. &check;
Inline links should always be underline, like this &check;

F. Social Hover
On hover state the social icons should not enlarge. &check;

G. Padding
There should be padding after the card ends when no load more CTA is added, as no more blogs are present for particular category. &check;

H. Home
On merative blog home page, resources tab should be shown selected with rainbow indicator &check;

### Article Page
Update breadcrumb arrow to arrow style in design &check;
Increase space below breadcrumbs to 74px &check;
Increase space above social link icons &check;
Main article image and content well should span 8 columns or 744px wide. I’m noticing the image width varies on different articles, some images are wider than others. (**Pending**, need to review again)
By line should only include name and read time. Please remove job title. Phase 2 we will want the name to link to an author page. (now will be fixed as part of #109)
TOC space between links should be 8px &check;
Decrease the space above the author read time, below article image to 48px. I’m noticing it varies on different articles, some have more space, than others &check;
Increase space below author and read time to 32px &check;
Remove underline on author name. This isn’t a link at the moment. When we do add links, the size of the link style should match the design. It looks very thick at the moment on some pages, some are thin, just inconsistent across pages &check;
Need example article without article image in order to QA it. 
Need example of pull quote to QA : You could use [Sample article page](https://main--merative--hlxsites.hlx.page/drafts/blog-article-page)
Need example of resources to QA &check; (**Phase2 Item**)
Need example of H3 with icon above them in the body to QA You could use [Sample article page](https://main--merative--hlxsites.hlx.page/drafts/blog-article-page)
Need example of video to QA &check; (**Phase2 Item**)
Increase space below the end of the article to  160px &check;
Increase space above subtitles to 96px  (**Phase2 Item**), need more info, what subtitles ?
Stand-alone and inline link style needs to match design. Please reference the link: https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=1228%3A3428&t=94cYzZRTK9PJC0mC-1 
Increase space above H3 titles to 64px :  &check; You could use [Sample article page](https://main--merative--hlxsites.hlx.page/drafts/blog-article-page)
Increase space above and below image to 64px &check;
Missing image caption ((**Phase2 Item**, need more info, dont see any image caption in the content)
Cards missing bottom radius curves &check;
Body copy style needs to match design &check;
Remove author titles in by-line (now will be fixed as part of #109)
May need to add some authoring guidelines on body character count. On all cards they are very long. &check;
Body text needs to span 744px or 8 columns on CTA &check;
Article without author headshot: the Merative logo icon is missing the circle stroke around it. Also the size looks like it needs to increase &check;

Link with comparative photos: https://merative.sharepoint.com/:w:/s/Merative.comWebsite/EUvtc33rppJDl9hYUTNZAH0BGGGHJDY5M-8gPPtxLzKeDQ?e=taEefm

**Comment by anabarcelona** [comment]
Hi @kunwarsaluja, Thank you! I'm hoping Sachin can help review these. Please work with him on the design QA process. I think it will be easiest to review each breakpoint separately, but ask Sachin how he'd like to work. You can reach out to him in our slack channel. His name is Sachin Meshram.

**Comment by sachinmesh** [comment]
Hi 

1. The spacing below merative blog text and divider rule should be 24px. (Pending, figma design suggests 32px)
     
<img width="950" alt="Screenshot 2023-01-31 at 12 48 47 PM" src="https://user-images.githubusercontent.com/124026684/215733729-0a93ef82-c466-4548-80f4-84fb9550ef12.png">

**Comment by sachinmesh** [comment]
HI @kunwarsaluja sharing the solutions for the pending bugs 

1. The spacing below merative blog text and divider rule should be 24px. (Pending, figma design suggests 32px)
<img width="950" alt="Screenshot 2023-01-31 at 12 48 47 PM" src="https://user-images.githubusercontent.com/124026684/215734026-c93c3d80-64bc-4c5c-8e37-d24a6f030560.png">

2. Please remove bar under Care Delivery, it’s not needed (Pending, need more info) - **the divider bar not needed above apply and reset.**
     
<img width="335" alt="Screenshot 2023-01-31 at 1 09 53 PM" src="https://user-images.githubusercontent.com/124026684/215734261-385ea6da-9bc1-469c-89a8-4a04eb0fe1b2.png">

3. Missing sticky Filters band. When a user scrolls the filters should be sticky at the top. (Pending, appears to be sticky. need more info)  - Scroll interaction shown here https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=474%3A2587&t=X7SJnoBhB8kaYjkc-4

    
<img width="743" alt="Screenshot 2023-01-31 at 12 59 24 PM" src="https://user-images.githubusercontent.com/124026684/215735076-681f4cc4-d8d9-4647-9142-a4adfa9eebc5.png">

4. Once scrolling the filters is sticky, but the drop shadow looks too light. Please reference design for colors. (Pending, need more info)
Same feedback for mobile.  - Shadow is dark in figma -  https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=474%3A2345&t=X7SJnoBhB8kaYjkc-4

<img width="472" alt="Screenshot 2023-01-31 at 1 11 32 PM" src="https://user-images.githubusercontent.com/124026684/215735490-4ecb17e8-a528-4696-aabe-d16ce706b40c.png">
CC: @anabarcelona

**Comment by anabarcelona** [comment]
Thanks @kunwarsaluja and @sachinmesh, Sachin will be finishing up the review of desktop. I'm going to start reviewing tablet across all breakpoints and adding it to the Design QA v2 doc. Linking that here: https://merative-my.sharepoint.com/:w:/p/smeshram/EROw-HoBsFBGkRDeCRXRSDEBEgwE0TNUrHenMhTvU8pyEg

**Comment by anabarcelona** [comment]
Please confirm you have access to view the doc above.

**Comment by anabarcelona** [comment]
We made good progress on design QA v2 ! If you have time, can you finish up the review for mobile? Thanks @sachinmesh

**Comment by sachinmesh** [comment]
Hi @anabarcelona Updated the QA v2 document with mobile reviews as well.

**Comment by kunwarsaluja** [comment]
Updated feedback for Design QA is provided by Sachin/Anna. Closing this in favor of https://github.com/hlxsites/merative/issues/119
