### ISSUE TITLE
Make the Blog Title always an H1 html tag

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#111]
Ensure all the blog titles are an HTML tag of H1. We'l want to keep the styling the same or aligned to our design standards.

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/111377779/214372201-86936941-5308-4995-acdf-710a057dc407.png">

**Comment by VladimirZaets** [comment]
Fixed pages: 
* [asking-right-ai-questions](https://main--merative2--hlxsites.hlx.page/blog/asking-right-ai-questions)
* [acc-2023-recap](https://main--merative2--hlxsites.hlx.page/blog/acc-2023-recap)
* [behavioral-telehealth]( https://main--merative2--hlxsites.hlx.page/blog/behavioral-telehealth)
* [beyond-klas-rankings-building-client-relationships-at-merative](https://main--merative2--hlxsites.hlx.page/blog/beyond-klas-rankings-building-client-relationships-at-merative)
* [cardiovascular-image-and-management-evolution](https://main--merative2--hlxsites.hlx.page/blog/cardiovascular-image-and-management-evolution)
* [commotio-cordis-damar-hamlin](https://main--merative2--hlxsites.hlx.page/blog/commotio-cordis-damar-hamlin)
* [connecting-with-the-clinical-development-community](https://main--merative2--hlxsites.hlx.page/blog/connecting-with-the-clinical-development-community)
* [covid-19-pandemic-and-patient-centricity-clinical-trials](https://main--merative2--hlxsites.hlx.page/blog/covid-19-pandemic-and-patient-centricity-clinical-trials)
* [decentralized-clinical-trials-closer-than-you-think](https://main--merative2--hlxsites.hlx.page/blog/decentralized-clinical-trials-closer-than-you-think)
* [democratizing-clinical-trials](https://main--merative2--hlxsites.hlx.page/blog/democratizing-clinical-trials)
* [employee-benefits-enrollments](https://main--merative2--hlxsites.hlx.page/blog/employee-benefits-enrollments)
* [equitable-clinical-practices-and-policy-breast-cancer-care](https://main--merative2--hlxsites.hlx.page/blog/equitable-clinical-practices-and-policy-breast-cancer-care)
* [five-questions-before-choosing-a-real-world-data-provider](https://main--merative2--hlxsites.hlx.page/blog/five-questions-before-choosing-a-real-world-data-provider)
* [focused-innovation-will-deliver-steady-progress-in-health-and-social-care](https://main--merative2--hlxsites.hlx.page/blog/focused-innovation-will-deliver-steady-progress-in-health-and-social-care)
* [government-social-program-management-works-best-with-integrated-services](https://main--merative2--hlxsites.hlx.page/blog/government-social-program-management-works-best-with-integrated-services)
* [healthcare-analytics-trane-eaton](https://main--merative2--hlxsites.hlx.page/blog/healthcare-analytics-trane-eaton)
* [health-equity-solutions-cant-go-with-gut](https://main--merative2--hlxsites.hlx.page/blog/health-equity-solutions-cant-go-with-gut)
* [human-centered-design-solves-business-problems](https://main--merative2--hlxsites.hlx.page/blog/human-centered-design-solves-business-problems)
* [introducing-marketscan-workspace](https://main--merative2--hlxsites.hlx.page/blog/introducing-marketscan-workspace)
* [introducing-zelta](https://main--merative2--hlxsites.hlx.page/blog/introducing-zelta)
* [ism-recap-2022](https://main--merative2--hlxsites.hlx.page/blog/ism-recap-2022)
* [is-real-world-data-the-real-deal](https://main--merative2--hlxsites.hlx.page/blog/is-real-world-data-the-real-deal)
* [klas-2023-merge-cardio-hemo](https://main--merative2--hlxsites.hlx.page/blog/klas-2023-merge-cardio-hemo)
* [merative-names-general-manager-for-merge](https://main--merative2--hlxsites.hlx.page/blog/merative-names-general-manager-for-merge)
* [merge-newsletter-april-2023](https://main--merative2--hlxsites.hlx.page/blog/merge-newsletter-april-2023)
* [merge-newsletter-march-2023](https://main--merative2--hlxsites.hlx.page/blog/merge-newsletter-march-2023)
* [micromedex-ranked-best-in-klas](https://main--merative2--hlxsites.hlx.page/blog/micromedex-ranked-best-in-klas)
* [payer-trends-healthcare-affordability](https://main--merative2--hlxsites.hlx.page/blog/payer-trends-healthcare-affordability)
* [person-centred-care-in-clinical-pharmacy](https://main--merative2--hlxsites.hlx.page/blog/person-centred-care-in-clinical-pharmacy)
* [price-transparency-aeob](https://main--merative2--hlxsites.hlx.page/blog/price-transparency-aeob)
* [price-transparency-machine-readable-files](https://main--merative2--hlxsites.hlx.page/blog/price-transparency-machine-readable-files)
* [questions-to-ask-when-managing-drug-shortages](https://main--merative2--hlxsites.hlx.page/blog/questions-to-ask-when-managing-drug-shortages)
* [reduce-spread-improve-productivity](https://main--merative2--hlxsites.hlx.page/blog/reduce-spread-improve-productivity)
* [sonoma-county-integrated-care](https://main--merative2--hlxsites.hlx.page/blog/sonoma-county-integrated-care)
* [test-article-1](https://main--merative2--hlxsites.hlx.page/blog/test-article-1)
* [the-conversation-around-dcts-is-shifting-again](https://main--merative2--hlxsites.hlx.page/blog/the-conversation-around-dcts-is-shifting-again)
* [where-do-you-start-when-tasked-with-delivering-social-security-benefits](https://main--merative2--hlxsites.hlx.page/blog/where-do-you-start-when-tasked-with-delivering-social-security-benefits)
