### ISSUE TITLE
Support Pages Migration

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#122]
https://www.merative.com/support
https://www.merative.com/support/artifact-dependencies-search-tool-for-code-removals
https://www.merative.com/support/guidance-on-customer-performance-issues
https://www.merative.com/support/micromedex-product-support-details
https://www.merative.com/support/micromedex-product-support-details/OrbitalRX-training-center
https://www.merative.com/support/micromedex-product-support-details/example-content-3
https://www.merative.com/support/marketscan-product-support-details
https://www.merative.com/support/health-insights-product-support-details
https://www.merative.com/support/other-product-support-details
https://www.merative.com/support/social-program-management-support-details
https://www.merative.com/support/social-program-management-support-details/social-program-management-8010-iFix2
https://www.merative.com/support/social-program-management-support-details/spm-release-notes-8011
https://www.merative.com/support/social-program-management-support-details/social-program-management-release-notes
https://www.merative.com/support/social-program-management-support-details/merative-social-program-management-release-notes
https://www.merative.com/support/imaging-product-support-details
https://www.merative.com/support/imaging-product-support-details/merge-healthcare-statements
https://www.merative.com/support/imaging-product-support-details/tuesdays-with-merative-imaging
https://www.merative.com/support/clinical-development-support-details

**Comment by kunwarsaluja** [comment]
- A bunch of pages are 404 on the live site but have restructured the content in sharepoint folders
- Few components are a work in progress, so will revisit once the custom styles are in.

**Comment by kunwarsaluja** [comment]
Current state of support pages : https://issue-122-support-pages--merative2--hlxsites.hlx.page/support

**Comment by venturewise** [comment]
https://main--merative2--hlxsites.hlx.page/support ready for review
https://main--merative2--hlxsites.hlx.page/support/micromedex-product-support-details ready for review
https://main--merative2--hlxsites.hlx.page/support/micromedex-product-support-details/orbitalrx-training-center ready for review
https://main--merative2--hlxsites.hlx.page/support/marketscan-product-support-details ready for review.
https://main--merative2--hlxsites.hlx.page/support/health-insights-product-support-details ready for review.
https://main--merative2--hlxsites.hlx.page/support/other-product-support-details ready for review.
https://main--merative2--hlxsites.hlx.page/support/social-program-management-support-details/social-program-management-release-notes ready for review.
https://main--merative2--hlxsites.hlx.page/support/social-program-management-support-details/merative-social-program-management-release-notes ready for review.
https://main--merative2--hlxsites.hlx.page/support/imaging-product-support-details ready for review.



**These can be QA'd but I don't have the link to the original page to compare against.**
https://main--merative2--hlxsites.hlx.page/support/artifact-dependencies-search-tool-for-code-removals
https://main--merative2--hlxsites.hlx.page/support/guidance-on-customer-performance-issues
https://main--merative2--hlxsites.hlx.page/support/social-program-management-support-details/social-program-management-release-notes
https://main--merative2--hlxsites.hlx.page/support/social-program-management-support-details/social-program-management-8010-ifix2



**These pages are not ready.**
https://main--merative2--hlxsites.hlx.page/support/micromedex-product-support-details/example-content-3
https://main--merative2--hlxsites.hlx.page/support/social-program-management-support-details/spm-release-notes-8011

**Comment by keith-kaplan** [comment]
Please hold off on QA'ing these pages. These are not in scope at the moment for Phase 2.
