### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#123]
https://www.merative.com/events
https://www.merative.com/events/ism
https://www.merative.com/events/rsna
https://www.merative.com/events/MDX-DYNAMED-Free-Trial-ASHP-Mid-Year
https://www.merative.com/events/SCOPE-2023-Merative-Clinical-Development
https://www.merative.com/events/conference-board
https://www.merative.com/products/carediscovery-electronic-quality-measures

**Comment by arumsey** [comment]
Use updated page design for events pages instead of what is on current site.

https://www.figma.com/file/FGFCs3L8fWfh7AnGUCi0RG/Marketo-Form-Landing-Page?t=N5xfbY1PDKKKzXHs-0

**Comment by arumsey** [comment]
https://main--merative2--hlxsites.hlx.page/events/chicago-payer-channel
https://main--merative2--hlxsites.hlx.page/events/himss-2023
https://main--merative2--hlxsites.hlx.page/events/conference-board
https://main--merative2--hlxsites.hlx.page/events/business-group-on-health
https://main--merative2--hlxsites.hlx.page/events/acc
https://main--merative2--hlxsites.hlx.page/events/scope-2023-merative-clinical-development
https://main--merative2--hlxsites.hlx.page/events/rsna
https://main--merative2--hlxsites.hlx.page/events/mdx-dynamed-free-trial-ashp-mid-year
https://main--merative2--hlxsites.hlx.page/events/ism
https://main--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference
