### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#127]
https://www.merative.com/

**Comment by kmurugulla** [comment]
While building the What we do section on the home page  , Could you please validate couple of things ?

- The Teaser List component is not rendering as expected
- The grid layout is adding white space which is adding a horizontal scroll for the page in the breakpoint > 768
- image

![image](https://user-images.githubusercontent.com/7944122/224407939-1a54ef65-9acc-41f0-94e3-902ed82bc28a.png)

**Comment by kmurugulla** [comment]
Here is the latest code - https://issue-127--merative2--hlxsites.hlx.page/ for the homepage and AFAIK there are two pending issues 

![](https://files.slack.com/files-pri/T23RE8G4F-F04U52X7UJK/image.png)


![](https://files.slack.com/files-pri/T23RE8G4F-F04UN34EFE0/image.png)

**Comment by arumsey** [comment]
Background arc can be added via section metadata.

**Comment by venturewise** [comment]
@arumsey I didn't see your comment here before my PR https://github.com/hlxsites/merative2/pull/39 where I added it with CSS. Let me know if the customer needs to be able to change out background images often via the Word doc and I will rework it in.
