### ISSUE TITLE
QA: PDF Viewer

### ISSUE THREAD

**Issue by krazykaplan14** [hlxsites/merative#141]
@amol-anand Ana and Sachin have done Design QA on the PDF viewer. Please document here - https://merative.sharepoint.com/:w:/s/Merative.comWebsite/EYiqYDIU1h1MqQAoleXRzVkBiHLQRuMjUxJKb8JBEcf1jQ?e=j1vC9Y

**Comment by helms-charity** [comment]
@arumsey Is this ticket completed? Sachin has been QA'ing the documents pages which include the PDF viewer, and so far he hasn't had any comments on it.
