### ISSUE TITLE
Mega Menu Header

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative#144]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1004204/226951159-b0363c0d-5029-4064-af71-38208c8f727c.png">

https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=496-6550&t=DLRVkL9fwo9gSd31-0

**Comment by amol-anand** [comment]
Based on our discussion with Keith - going by what is in production now on the site and not the search icon etc.. 

It looks like this
![Screenshot 2023-04-13 at 4 07 36 PM](https://user-images.githubusercontent.com/7074782/231871551-99b57040-e2e6-439c-af13-a95489b10ec5.png)
![Screenshot 2023-04-13 at 4 07 51 PM](https://user-images.githubusercontent.com/7074782/231871553-83caf590-7622-4f42-bd98-a12753ead417.png)
![Screenshot 2023-04-13 at 4 07 59 PM](https://user-images.githubusercontent.com/7074782/231871556-a5be8f23-1cc6-45c5-892d-ed58570d5b0e.png)
![Screenshot 2023-04-13 at 4 09 04 PM](https://user-images.githubusercontent.com/7074782/231871907-91c043ac-6748-4863-8a0d-e4b61da63ebe.png)
