### ISSUE TITLE
Need consistent treatment of the "eyebrow" section headings

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#145]
I have seen 3 different treatments of the small, uppercase section headings just on the home page.
I propose they are all authored on the pages as H4 across the board, but will leave it to the group to decide. (note that there are H4s used in other places, such as the footer, but I think those can be styled specifically).

Current iterations seen on just the home page:
1. NEWS has it in CSS only
`.cards.newscard .cards-card-body::before {
    font-size: var(--font-size-11);
    letter-spacing: 3.2px;
    content: "NEWS";
    padding-top: var(--spacer-element-10);
    font-family: var(--sans-serif-font-medium);
}`

2. DECREASE under the 32% stat is a too-ambiguous P tag:
`main .section-bottom .columns-2-cols > div > :nth-child(2) p:nth-of-type(1) {
    font-family: var(--sans-serif-font-medium);
    font-size: var(--font-size-11);
    letter-spacing: 0.2em;
    text-transform: uppercase;
}`

3. WHAT WE DO is a fairly specific H4, which is my preference
`main .section.what-we-do > .default-content-wrapper > h4 {
    font-family: var(--sans-serif-font-medium);
    font-size: 14px;
    letter-spacing: 3.2px;
    line-height: var(--line-height-120);
    color: #20201f;
    margin-bottom: 32px;
}`

**Comment by kunwarsaluja** [comment]
Do we want this detailed info in a basic authoring guide ? Authors might not even understand this and maybe we can have a discussion with Merative design guys to make it consistent if possible ?

OR

have a separate page for all these 1 offs so the merative team is aware. wdyt ?

**Comment by venturewise** [comment]
@amol-anand Are we going to have page "templates', with placeholder text for the customer to refer to?

**Comment by arumsey** [comment]
Can this issue be resolved yet?
