### ISSUE TITLE
Build pages: root, terms, privacy, newsroom, leadership

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#153]
By end of this week, if we can get these out, we can send it for QA and start the go-live proceedings for phase 2 next week. 

/
/terms
/privacy
/newsroom
/leadership

**Comment by venturewise** [comment]
https://main--merative2--hlxsites.hlx.page/terms is ready for review.
https://main--merative2--hlxsites.hlx.page/privacy is ready for review

**Comment by venturewise** [comment]
@amol-anand do you want to take a look at these links before sending to the client?

**Comment by amol-anand** [comment]
good to go

**Comment by anabarcelona** [comment]
**Desktop: 1440**  

**A. Leadspace** 

1. Top navigation can be updated when it's ready. 
3. Left & right padding should be 156px 

<img width="602" alt="image" src="https://user-images.githubusercontent.com/47047225/229827814-387e25f4-828b-49d4-bff2-94fda051d867.png">

**Comment by venturewise** [comment]
@anabarcelona can you specify what item needs left and right padding of 156px?

**Comment by arumsey** [comment]
Top navigation menu will be completed in Phase 3. https://github.com/hlxsites/merative/issues/144

**Comment by sachinmesh** [comment]
149px its showing on leadspace


<img width="1396" alt="image" src="https://user-images.githubusercontent.com/124026684/229837729-cb9a950a-9d28-4f65-89e1-fff7e1ac3894.png">

**Comment by venturewise** [comment]
I see. We're going to concentrate on the 1200px content width in my screen shot, since folks can have all differing monitor widths. 
![image](https://user-images.githubusercontent.com/3883795/229840769-0162d1a6-76c5-4391-bc24-ca988745c49c.png)

**Comment by sachinmesh** [comment]
**Terms & conditions page Design QA v1** 

 
 

**For reference:**  

Dev on left / Design on the right  

  

**Figma Design:**  

https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144-47867&t=ioM89z7PTF32MfAj-4 

 

 
 

  

**Dev:**  

https://main--merative2--hlxsites.hlx.page/terms 

 

 
 

**Desktop: 1440** 

 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/124026684/230041885-74e1b124-8323-4020-95fb-973715bf6291.png">


 

                            

 
 

1. The spacing between the titles on left and the body copy on right should be 120px. 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/124026684/230042038-6fd39deb-9900-42f7-9081-b2790bcf238f.png">

2. Some text can be seen in all caps. 


 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/124026684/230042265-71fd4ac4-17d7-494c-83f0-bff44ba35a6a.png">


3. The Spacing between title and overview should be 64px. Its 68px now. 

 

 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/124026684/230042381-b6576077-f3bb-47e4-84a1-f483198f8617.png">


 

4.The spacing between each paragraphs should be 64px, its 60px now. 

 

 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/124026684/230042495-48f2d128-75d5-4ce8-9083-00059adfdb8c.png">


 

5.. The spacing between the last paragraph and the footer should be 160px.

**Comment by sachinmesh** [comment]
**Newsroom page Design QA v1** 

 
 

**For reference:**  

Dev on left / Design on the right  

  

**Figma Design:**  

https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144-48333&t=ioM89z7PTF32MfAj-4 

 

  

**Dev:**  

https://main--merative2--hlxsites.hlx.page/newsroom 

 
 

**Desktop: 1440** 

 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/124026684/230045025-80568929-45a5-4c2f-bae7-71ec23e45f7b.png">

 

             

 
 
 

1. The spacing between the title and the cards should be 48px. 

 
 
 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/124026684/230045665-58a0e29a-16ef-47ae-9f56-8fdb9761432c.png">

 
 

       

 
 

2. The width of the icon component  should be 320px. 

3. The spacing between the title and the inline link should be 32px. 

 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/124026684/230045798-1103ffb1-9711-47dd-b14a-665b49181245.png">

 
 
 

           

4. Globe icon to the heading should be 24px. 

5. Heading to inline link should be 32px. 

6. Hover state outward arrow missing. 

7. Contact us CTA design is wrong.

**Comment by sachinmesh** [comment]
**Leadership page Design QA v1** 

 
 

**For reference:**  

Dev on left / Design on the right  

  

**Figma Design:**  

https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144-46379&t=DMarj7RtEte8VqiI-4 

 
 

  

**Dev:**  

https://main--merative2--hlxsites.hlx.page/leadership 

 

 
 

**Desktop: 1440**  

 
 

**A. Leadspace** 

 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/124026684/230050188-e910809c-dd68-4953-8365-9d00ac77f4da.png">

 

         

 
 

1. The spacing above the heading should be 96px. 

2. The semicircle image should be bottom aligned here. There’s  a gap visible below the image. 

 
 
 

**B. Leadership card** 

 
 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/124026684/230050611-5c0163ca-a9fb-4cff-b9b7-f62ae18ced6e.png">


         

 
 

3. The width of the cards should be 360px. 

4. The leader name font style should be H3 32px Source serif pro. 

5. The spacing between each card should be 24px. 

6. The spacing between the photo and the leader name should be 32px. 

7. The spacing between leader name and designation should be 16px. 

8. Extra 48px spacing can be seen between the last cards with the footer. It should be 160px.

**Comment by sachinmesh** [comment]
Sharing Careers Design QA
[Careers page Design QA v1.pdf](https://github.com/hlxsites/merative/files/11178380/Careers.page.Design.QA.v1.pdf)
CC: @anabarcelona
