### ISSUE TITLE
Related Resources

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#157]
Related Resources needs two updates -
1. add an option to scroll (default stack)
2. add the ability to also handle blog articles automatically

**Comment by venturewise** [comment]
@amol-anand also not sure how you want to handle arrows? The cards on the Newsroom page have the 45deg angle ones in Figma, but the ones on Related Resources are facing right.
![image](https://user-images.githubusercontent.com/3883795/228954057-f91202d8-ce0f-488c-9c4a-0a253c4576ad.png)
