### ISSUE TITLE
Accordion borders are misplaced

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative#165]
An accordion item should have a border below it when closed. A wider gradient boder should appear above when open. When there is only one entry in an accordion there should only be a border below.

**Comment by VladimirZaets** [comment]
@arumsey I add border below, but didn't get what mean "A wider gradient boder should appear above when open". Looks like it already exists, or can you please explain what you mean?

<img width="1197" alt="Screen Shot 2023-04-03 at 6 27 32 PM" src="https://user-images.githubusercontent.com/8035672/229648253-979ab572-267e-4803-9314-88ed6fe28ef8.png">
<img width="1202" alt="Screen Shot 2023-04-03 at 6 27 22 PM" src="https://user-images.githubusercontent.com/8035672/229648254-160dae05-3276-46a6-98be-83111419f8ee.png">

**Comment by arumsey** [comment]
@VladimirZaets The graident border above has already been fixed. The only remaining issue is when you have a single entry accordion. Whenm this occurs the grey border is above the entry instead of below when in the closed position.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/1004204/229802595-b9553d26-3f13-47fc-9330-3e1cb46cbe8f.png">
