### ISSUE TITLE
Remove px height from quarter/half circle images

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#170]
Per Ana, the height may change but the width will be 552px. [1]
I had added px heights on them to account for Lighthouse content shift scores, but will try aspect ratio boxes instead.

[1]
![image](https://user-images.githubusercontent.com/3883795/230385943-973508e7-4450-4fdf-a3bb-965f67d46240.png)

**Comment by arumsey** [comment]
Are all images supposed to have an aspect ratio of 1 / 1 or do we need to be more flexible than that?

This may be addressed by https://github.com/hlxsites/merative/issues/169

**Comment by venturewise** [comment]
I think this is fixed.
