### ISSUE TITLE
QA: /company

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#173]
[Company page Design QA v1.docx](https://github.com/hlxsites/merative/files/11193653/Company.page.Design.QA.v1.docx)

@sachinmesh I made a new issue for your Company page Word doc. We can continue the review conversation via these issues and then close them when the page is accepted.

https://main--merative2--hlxsites.hlx.page/company

**Comment by arumsey** [comment]
@sachinmesh https://main--merative2--hlxsites.hlx.page/company is ready for another review.

**Comment by keith-kaplan** [comment]
@arumsey can we evaluate how the teaser component? It looks like it's pulling in info based on URL. That's a nice feature, but we'd like to be able to author this component with a title, description, CTA. As you can see the page titles often times have "| Merative". What other options do we have for this?

**Comment by arumsey** [comment]
@sachinmesh Could you elaborate on what is wrong with the CTA design? Also, is the CTA button design different from the Primary button design or should they be identical?

I did notice that the space after the icon should be 16px and not 24px so I made that change. Are there still additional fixes that need to be applied to ALL CTA/Primary buttons?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1004204/231762782-f46a7f52-d97d-41cb-abd7-8079b3cd2dfd.png">

<img width="217" alt="image" src="https://user-images.githubusercontent.com/1004204/231762855-4f379722-6889-4a4b-9059-035411c16f50.png">

**Comment by arumsey** [comment]
@sachinmesh Should the left content of the Leadspace block always be vetically centered?

Like this?

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/1004204/231766992-66ad0fab-8813-4a53-acb7-66aacd375f6e.png">

**Comment by helms-charity** [comment]
@sachinmesh 
On this leadspace in Tablet -- I measured all the comps, and in tablet, the left text was usually 64px from bottom. The top margin was fluid.

![image](https://user-images.githubusercontent.com/3883795/231772179-ffa4b3c2-56a9-4543-aa94-5484a20b8543.png)

**Comment by arumsey** [comment]
> @arumsey can we evaluate how the teaser component? It looks like it's pulling in info based on URL. That's a nice feature, but we'd like to be able to author this component with a title, description, CTA. As you can see the page titles often times have "| Merative". What other options do we have for this?

@keith-kaplan You would like the `teser-list` to allow for both automatic title/description/CTA as well as being fully authorable too?

**Comment by keith-kaplan** [comment]
If we can do that, that would be nice. If we had to prioritize I'd say I'd rather it authorable because it's automatically pulling in page title, descriptions, and automating the CTA the content it pulls in may not be what we want it to be.

**Comment by sachinmesh** [comment]
> @sachinmesh Could you elaborate on what is wrong with the CTA design? Also, is the CTA button design different from the Primary button design or should they be identical?
> 
> I did notice that the space after the icon should be 16px and not 24px so I made that change. Are there still additional fixes that need to be applied to ALL CTA/Primary buttons?
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/1004204/231762782-f46a7f52-d97d-41cb-abd7-8079b3cd2dfd.png">
> 
> <img alt="image" width="217" src="https://user-images.githubusercontent.com/1004204/231762855-4f379722-6889-4a4b-9059-035411c16f50.png">

This is correct. All CTAs with an icon should have these specifications on all pages.

**Comment by arumsey** [comment]
> If we can do that, that would be nice. If we had to prioritize I'd say I'd rather it authorable because it's automatically pulling in page title, descriptions, and automating the CTA the content it pulls in may not be what we want it to be.

I just confirmed that teaser list is already authorable. The title, description and link title can all be customized by the author.

**Comment by arumsey** [comment]
@sachinmesh I think the only remaining issue is regarding Leadspace layout.

https://github.com/hlxsites/merative/issues/173#issuecomment-1506958241

**Comment by sachinmesh** [comment]
> @sachinmesh On this leadspace in Tablet -- I measured all the comps, and in tablet, the left text was usually 64px from bottom. The top margin was fluid.
> 
> ![image](https://user-images.githubusercontent.com/3883795/231772179-ffa4b3c2-56a9-4543-aa94-5484a20b8543.png)

The right image is always bottom aligned in tablet even if the length in text side increases.
CC: @anabarcelona

**Comment by helms-charity** [comment]
@sachinmesh I am not seeing the right image leaving the bottom in any breakpoint. I was addressing your point 21 in the PDF:
![image](https://user-images.githubusercontent.com/3883795/232010673-a643647a-08d0-46c5-80db-a99fe7a09b5c.png)

**Comment by sachinmesh** [comment]
> @sachinmesh I am not seeing the right image leaving the bottom in any breakpoint. I was addressing your point 21 in the PDF: ![image](https://user-images.githubusercontent.com/3883795/232010673-a643647a-08d0-46c5-80db-a99fe7a09b5c.png)

Here i guess at this breakpoint extra spacing on both ends.

**Comment by helms-charity** [comment]
@sachinmesh thank you, but I'm still a bit confused.
Can you be more specific on your comment of "Here i guess at this breakpoint extra spacing on both ends."? 

Are you saying YES to Anthony's question "Should the left content of the Leadspace block always be vetically centered?"  at https://github.com/hlxsites/merative/issues/173#issuecomment-1506928763 ?

And if so, is this your direction for ALL leadspace left content at the Tablet size?

**Comment by sachinmesh** [comment]
> @sachinmesh thank you, but I'm still a bit confused. Can you be more specific on your comment of "Here i guess at this breakpoint extra spacing on both ends."?
> 
> Are you saying YES to Anthony's question "Should the left content of the Leadspace block always be vetically centered?" at [#173 (comment)](https://github.com/hlxsites/merative/issues/173#issuecomment-1506928763) ?
> 
> And if so, is this your direction for ALL leadspace left content at the Tablet size?

Here you can see the layout from top merative logo and meet merative alignment.

**Comment by arumsey** [comment]
> > @sachinmesh thank you, but I'm still a bit confused. Can you be more specific on your comment of "Here i guess at this breakpoint extra spacing on both ends."?
> > Are you saying YES to Anthony's question "Should the left content of the Leadspace block always be vetically centered?" at [#173 (comment)](https://github.com/hlxsites/merative/issues/173#issuecomment-1506928763) ?
> > And if so, is this your direction for ALL leadspace left content at the Tablet size?
> 
> Here you can see the layout from top merative logo and meet merative alignment.

@sachinmesh What are you expecting to see between the top Merative logo and the Meet Merative text?

In this screenshot the `Leadspace` block is at its maximum width and is cenered aligned on the page.
The extra space above the "Meet Merative" text is due to the height of the Leadspace image which is determined by its width in order to maintain the correct aspect ratio.

**Comment by sachinmesh** [comment]
From 1199px till 768px resolution, there's this padding. the top navigation bar and the layout below it is not aligned, thats what i was pointing out.

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/124026684/233602870-e481330e-c4b5-4697-b1be-a32d7ae54246.png">

CC: @keith-kaplan @anabarcelona

**Comment by helms-charity** [comment]
Thanks so much, @sachinmesh for that detail. I just checked, and this is not a defect. The tablet content is fixed at the width that was in your Figma designs for every page. However, the header (and footer) is allowed to be fluid.
