### ISSUE TITLE
QA: /terms, /privacy

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#176]
These pages are essentially using the same styling/template.
There is only a Word doc currently for /terms :

[Terms & conditions page Design QA v1.docx](https://github.com/hlxsites/merative/files/11193829/Terms.conditions.page.Design.QA.v1.docx)
https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144-47867&t=ioM89z7PTF32MfAj-4
https://main--merative2--hlxsites.hlx.page/terms

https://main--merative2--hlxsites.hlx.page/privacy

**Comment by sachinmesh** [comment]
Sharing QA document 
[Terms & conditions page Design QA v2.pdf](https://github.com/hlxsites/merative/files/11272950/Terms.conditions.page.Design.QA.v2.pdf)

Majorly font style for the left text should be H5 i.e 16px Alliance No.1 regular and text on right paragraph should be 16px Alliance No.1 Light.
At some places the text can be seen in uppercase and font style is wrong also.
CC: @anabarcelona

**Comment by helms-charity** [comment]
@sachinmesh these changes are addressed via https://github.com/hlxsites/merative2/pull/111.

[2. Some text can be seen in all caps -- Won't fix. The text being uppercase is how it was imported, so it can be changed by authoring. 
[4. The Spacing between title and overview should be 64px
[6. The spacing between each paragraphs should be 64px

**Comment by helms-charity** [comment]
@keith-kaplan you might want to have someone proofread the text in these 2 pages. Some areas are all caps (seems to be on purpose). Otherwise the items flagged in this ticket should be complete.

**Comment by keith-kaplan** [comment]
We can close this out. The all caps stuff is not a big deal and is what our legal team has in their copy docs. We don't have worry about this.
