### ISSUE TITLE
QA: /newsroom

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#177]
[Newsroom page Design QA v1.docx](https://github.com/hlxsites/merative/files/11193855/Newsroom.page.Design.QA.v1.docx)
https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144-48333&t=ioM89z7PTF32MfAj-4
https://main--merative2--hlxsites.hlx.page/newsroom

**Comment by sachinmesh** [comment]
Sharing round 2 of QA
[Newsroom page Design QA v2.pdf](https://github.com/hlxsites/merative/files/11233556/Newsroom.page.Design.QA.v2.pdf)
CC : @anabarcelona

**Comment by helms-charity** [comment]
@sachinmesh, regarding item #2. what should the gap space be between the icon components? I had 64px, which made each of the 3 columns 333px. But on the Figma page, I see 79px gap with 305px width.

![image](https://user-images.githubusercontent.com/3883795/232077155-6c5e66bc-5528-4e3c-a38b-4fc765997a7a.png)

It looks like if I use a gap of 83px between the columns, they will be 320.67px wide each. Does that sound right to you?
![image](https://user-images.githubusercontent.com/3883795/232081170-aefac064-d9cd-446a-892b-89ba8c8f8a3e.png)

**Comment by helms-charity** [comment]
Update: I have merged in the requested changes.

**Comment by arumsey** [comment]
@venturewise is this page ready for review again?

**Comment by helms-charity** [comment]
Yes, @sachinmesh you can review again.

**Comment by helms-charity** [comment]
@sachinmesh and @keith-kaplan, let me know if we can close this ticket.

**Comment by sachinmesh** [comment]
Hi Team,
Only the width is needed to be fixed here.

The width of the icon component should be 320px wide and padding between 2 icon components should be 64px.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/124026684/235122834-58aca62b-ed60-4457-8972-cc38e8fb5817.png">

CC: @keith-kaplan @anabarcelona

**Comment by helms-charity** [comment]
@sachinmesh @keith-kaplan @anabarcelona,
Note that my same comment can be applied to the 3 columns of circle + text use case on https://main--merative2--hlxsites.hlx.page/careers ...

I'm conflicted on how to address the 3 column content when the width of desktop page content is 1128px total.

[This Newsroom Figma page mockup](https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9144%3A48332&t=nZXqm1bAdS24aEc7-1): has numbers of 305px width columns + 79px gap between. This adds up to 1073px width of the column block.
![image](https://user-images.githubusercontent.com/3883795/235138928-2c055eaf-105b-43d4-a21f-1bf3c057169a.png)

The screenshot/measurements Sachin pasted above has numbers that only equal 1088 px width of the column block.
![image](https://user-images.githubusercontent.com/3883795/235140029-770ab120-d98c-4a6d-a196-f07c1e25e248.png)

So I would think we would want to choose between these three options:
1. Use 64px gap
1128px total page content width --> subtract the (2 x 64px) gaps = 1000px. Then divide by 3 columns = **333px columns**

2. Use 79px gap
1128px total page content width --> subtract the (2 x 79px) gaps = 970px. Then divide by 3 columns = **323px columns**

3. Use 320px columns
1128px total page content width --> subtract the (3 x 320px) columns = 168px, divide by 2 gaps = **84px gaps**

Thanks for your guidance here.

**Comment by arumsey** [comment]
Since there is a fixed width for every breakpoint and a fixed gap of `64px` between each column shouldn't that be enough? Each column will then grow to take up all the remaining space available. Adding too many fixed widths everywhere will make it harder for the layout to adapt to a variety of screen sizes within a breakpoint. This is especially evident on desktop where the screen width can be any value.

**Comment by arumsey** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/1004204/235144487-fa3e44d9-2152-4ce5-9979-bb22e1ca5d15.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1004204/235145020-5fbd51cf-9b44-4118-af07-dd9acff90f21.png">

**Comment by arumsey** [comment]
> So I would think we would want to choose between these three options:
> 
> 1. Use 64px gap
>    1128px total page content width --> subtract the (2 x 64px) gaps = 1000px. Then divide by 3 columns = **333px columns**
> 2. Use 79px gap
>    1128px total page content width --> subtract the (2 x 79px) gaps = 970px. Then divide by 3 columns = **323px columns**
> 3. Use 320px columns
>    1128px total page content width --> subtract the (3 x 320px) columns = 168px, divide by 2 gaps = **84px gaps**
> 
> Thanks for your guidance here.

Whatever choice is made will be made across ALL content-band usage and not just `/newsroom`.

**Comment by keith-kaplan** [comment]
@arumsey @venturewise I looked at our design system and saw the screenshot below. This component in our design system is called our content band list (it has icons). There is some inconsistencies in the design system where in one frame it's showing 320px width/64px gap and in other frames where it's showing 305px width/78px gap.

Agreed with @arumsey  this change needs to follow the grid and is applied to anywhere else this block is used on the website.

https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=1459%3A14993&t=bqHtmnGO1ROcNxcf-1


Going to ask Ana about this and see what the direction is.

**Comment by keith-kaplan** [comment]
Spoke to Ana. The width of each card should be 320px w/ 64px gap. If a third card is present, 40px is added to the right of the card. See the screenshot below. This should be applied to all instances.

(320x3)+(64x2)+40=1128

<img width="882" alt="image" src="https://user-images.githubusercontent.com/111377779/235458431-ef9f5455-fcb9-4eae-95a1-b077ceb1b6df.png">

**Comment by helms-charity** [comment]
Thanks for the notes, I've made the change -- please have another look.
@keith-kaplan

**Comment by keith-kaplan** [comment]
Looks great. Thanks.
