### ISSUE TITLE
QA: /contact

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative#186]
- https://main--merative2--hlxsites.hlx.page/contact
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/Shared%20Documents/website/[contact.docx](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/Shared%20Documents/website/contact.docx?d=w0b381c6b6d0d49e3b11a48227dccfdc5&csf=1&web=1&e=wfcO2U)?d=w0b381c6b6d0d49e3b11a48227dccfdc5&csf=1&web=1&e=wfcO2U
- https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=12294-55624&t=2oTIRN7TYtMANW7s-0

**Comment by arumsey** [comment]
@sachinmesh ready for review

**Comment by helms-charity** [comment]
@keith-kaplan and @sachinmesh, this is ready for your review.

**Comment by sachinmesh** [comment]
Hi Team,
Design QA for contact us here

Heading font style should be H1 – Source serif pro 64px light.
Spacing between Title and bodytext should be 24px.
Font styles for Address, Support and Phone should be H4 - Alliance No.1 21px medium.
Submit CTA should have 48px spacing above.

CC: @keith-kaplan @anabarcelona

**Comment by arumsey** [comment]
- Heading font style should be H1 – Source serif pro 64px light. **FIXED**
- Spacing between Title and bodytext should be 24px. **FIXED**

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1004204/235153952-c73503e6-bee5-48ea-8003-fc87a6cfc43e.png">

- Font styles for Address, Support and Phone should be H4 - Alliance No.1 21px medium. **FIXED**

<img width="329" alt="image" src="https://user-images.githubusercontent.com/1004204/235154020-3f489362-7f81-4b93-822d-0b9e72d42dac.png">

- Submit CTA should have 48px spacing above. **FIXED**

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1004204/235153819-d89144cf-2b46-4fca-b131-828375eb421d.png">
