### ISSUE TITLE
QA: /offers/benefits-mentor-demo

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative#188]
https://main--merative2--hlxsites.hlx.page/offers/benefits-mentor-demo

https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B8912A332-B58F-4EDF-9E32-56EA572BBED8%7D&file=benefits-mentor-demo.docx&action=default&mobileredirect=true

Figma that shows the CTA at the bottom with a picture:
https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=1402%3A12379&t=RoYBxzHx9z5JFBvR-1

**Comment by helms-charity** [comment]
@arumsey is this ready for customer review?

**Comment by arumsey** [comment]
@venturewise This page just needed its Marketo block updated and a Metadata block added. Those have both been compelted now.

**Comment by helms-charity** [comment]
@keith-kaplan this demo page is ready for you to review.

**Comment by keith-kaplan** [comment]
Looks great.
