### ISSUE TITLE
authoring: /events/ism, /rsna, /mdx..., /scope-2023..., /conference-board, /acc, /business-group..., /himss-2023

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#209]
1. Case studies PDFs need to be authored:

- https://main--merative2--hlxsites.hlx.page/events/ism
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7BBDBED3CB-5DE5-4A8E-8436-937D17689DD8%7D&file=ism.docx&action=default&mobileredirect=true

2. Fix PDF link

- https://main--merative2--hlxsites.hlx.page/events/rsna
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B434D7C9B-19F0-4A02-B79C-C9D559E32E2D%7D&file=rsna.docx&action=default&mobileredirect=true

4. large link styles changes needed:

- https://main--merative2--hlxsites.hlx.page/events/mdx-dynamed-free-trial-ashp-mid-year
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B09304F87-E70F-435D-ACE8-FD1C737A57D8%7D&file=mdx-dynamed-free-trial-ashp-mid-year.docx&action=default&mobileredirect=true

5. CTA button, case studies PDFs need to be authored:

- https://main--merative2--hlxsites.hlx.page/events/scope-2023-merative-clinical-development
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7BC16A9E51-6D44-41A8-971F-E5D428CA3618%7D&file=scope-2023-merative-clinical-development.docx&action=default&mobileredirect=true

6. Needs a button authored:

- https://main--merative2--hlxsites.hlx.page/events/conference-board
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B6BEBDE5A-E2FC-42F0-8066-328F02F2FF3A%7D&file=conference-board.docx&action=default&mobileredirect=true

7. Check font size in "find us" section:

- https://main--merative2--hlxsites.hlx.page/events/acc
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B336E6D48-B908-4B55-A4AA-7CAFED848777%7D&file=acc.docx&action=default&mobileredirect=true

8. PDF in resources needs to be manually authored?

- https://www.merative.com/events/business-group-on-health
- https://main--merative2--hlxsites.hlx.page/events/business-group-on-health
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B7C9C4E8F-6CF0-4C4E-A6FB-B18F7557AE8D%7D&file=business-group-on-health.docx&action=default&mobileredirect=true

9. Resources need authoring

- https://www.merative.com/events/himss-2023
- https://main--merative2--hlxsites.hlx.page/events/himss-2023
- https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B95E3BCFE-82C1-4BAC-943D-4F8939E1830B%7D&file=himss-2023.docx&action=default&mobileredirect=true

**Comment by arumsey** [comment]
- [x] https://main--merative2--hlxsites.hlx.page/events/ism
- [x] https://main--merative2--hlxsites.hlx.page/events/rsna
- [ ] https://main--merative2--hlxsites.hlx.page/events/mdx-dynamed-free-trial-ashp-mid-year 
- [x] https://main--merative2--hlxsites.hlx.page/events/scope-2023-merative-clinical-development
- [x] https://main--merative2--hlxsites.hlx.page/events/conference-board
- [x] https://main--merative2--hlxsites.hlx.page/events/acc
- [x] https://www.merative.com/events/business-group-on-health
- [x] https://www.merative.com/events/himss-2023

**Comment by helms-charity** [comment]
Once this is merged https://github.com/hlxsites/merative2/pull/92 , I think you can create a QA ticket for the customer?
