### ISSUE TITLE
QA: /events

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#210]
All migrated event pages form merative.com.

**Pages**

- https://main--merative2--hlxsites.hlx.page/events/acc
- https://main--merative2--hlxsites.hlx.page/events/business-group-on-health
- https://main--merative2--hlxsites.hlx.page/events/chicago-payer-channel
- https://main--merative2--hlxsites.hlx.page/events/conference-board
- https://main--merative2--hlxsites.hlx.page/events/himss-2023
- https://main--merative2--hlxsites.hlx.page/events/ism
- https://main--merative2--hlxsites.hlx.page/events/mdx-dynamed-free-trial-ashp-mid-year
- https://main--merative2--hlxsites.hlx.page/events/rsna
- https://main--merative2--hlxsites.hlx.page/events/scope-2023-merative-clinical-development

**Sharepoint Folder**
- https://merative.sharepoint.com/:f:/r/sites/Merative.comWebsite/Shared%20Documents/website/[events](https://merative.sharepoint.com/:f:/r/sites/Merative.comWebsite/Shared%20Documents/website/events?csf=1&web=1&e=GzO931)?csf=1&web=1&e=GzO931

**Comment by arumsey** [comment]
@sachinmesh ready for review

**Comment by keith-kaplan** [comment]
I'm going through to ensure metadata and success URLs on marketo forms are correct.

**Comment by helms-charity** [comment]
@keith-kaplan let us know if this ticket is good to be closed.

**Comment by keith-kaplan** [comment]
Yes, we should be good to close these out. Thank you.
