### ISSUE TITLE
PDF files missing from multiple brief pages

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#212]
These pages give an error for the PDF viewer, and the PDF is a 404 on the live site as well:
1.
https://www.merative.com/documents/brief/DynaMed_and_Micromedex_with_Watson_solution_brief
https://www.merative.com/content/dam/merative/documents/brief/DynaMed_and_Micromedex_with_Watson_solution_brief.pdf

2.
https://main--merative2--hlxsites.hlx.page/documents/brief/mer-3036706726-merative-factsheet-aug2022
https://www.merative.com/content/dam/merative/documents/brief/mer-3036706726-merative-factsheet-aug2022.pdf

3.
https://main--merative2--hlxsites.hlx.page/documents/brief/micromedex-with-watson-solution-brief
https://www.merative.com/content/dam/merative/documents/brief/micromedex-with-watson-solution-brief.pdf

**Comment by helms-charity** [comment]
@keith-kaplan , this one is for your team I think.

**Comment by venturewise** [comment]
Also missing is the PDF for https://main--merative2--hlxsites.hlx.page/documents/brief/mer-3036706726-merative-factsheet-aug2022

https://www.merative.com/content/dam/merative/documents/brief/mer-3036706726-merative-factsheet-aug2022.pdf

**Comment by helms-charity** [comment]
Also, this page doesn't have a description (not sure if that is intentional) https://main--merative2--hlxsites.hlx.page/documents/brief/orbitalrx-solution-brief

This page has a repeat of title and description: https://main--merative2--hlxsites.hlx.page/documents/brief/price-transparency-brief

**Comment by keith-kaplan** [comment]
@venturewise  i'll take a look today.

**Comment by keith-kaplan** [comment]
New links are here:
1. https://main--merative2--hlxsites.hlx.page/content/dam/merative/documents/brief/dynamedex-solution-brief.pdf
3. https://main--merative2--hlxsites.hlx.page/content/dam/merative/documents/brief/micromedex-solution-brief.pdf


We don't need to worry about putting a PDF Viewer page for the old Merative fact sheet.

**Comment by helms-charity** [comment]
I updated the PDF viewer URL on the two pages using these, and the PDF is showing now:
https://www.merative.com/content/dam/merative/documents/brief/dynamedex-solution-brief.pdf
https://www.merative.com/content/dam/merative/documents/brief/micromedex-solution-brief.pdf

Here are the Word docs for ref:
https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B0747D404-FC83-46E2-AED8-28B75CD34DCE%7D&file=dynamed-and-micromedex-with-watson-solution-brief.docx&action=default&mobileredirect=true

https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B72BE2F42-9F5B-4C81-8767-AE918DE24E32%7D&file=micromedex-with-watson-solution-brief.docx&action=default&mobileredirect=true

**Comment by helms-charity** [comment]
@keith-kaplan those 2 pages still need metadata to be looked at (I see read time is blank, for example).

**Comment by keith-kaplan** [comment]
Thanks. I can get those updated.

**Comment by keith-kaplan** [comment]
Updated.

**Comment by keith-kaplan** [comment]
We can complete this one
https://main--merative2--hlxsites.hlx.page/documents/brief/dynamed-and-micromedex-with-watson-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/micromedex-with-watson-solution-brief

**Comment by helms-charity** [comment]
Are you going to delete the 2022 fact sheet from Sharepoint?

**Comment by keith-kaplan** [comment]
Done.
