### ISSUE TITLE
QA: /documents/briefs/*

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#213]
All of these have the same layout. They have all been updated to use the new cta fragment. (https://main--merative2--hlxsites.hlx.page/fragments/cta-schedule-consult )

https://main--merative2--hlxsites.hlx.page/documents/brief/7-strategies-to-optimize-health-plan-performance
https://main--merative2--hlxsites.hlx.page/documents/brief/8-use-cases-for-patient-engagement-with-phytel
https://main--merative2--hlxsites.hlx.page/documents/brief/9-strategies-to-address-population-health-challenges
https://main--merative2--hlxsites.hlx.page/documents/brief/child-welfare-saas
https://main--merative2--hlxsites.hlx.page/documents/brief/child-welfare-saas-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/citizen-engagement-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/clinical-developement-solution-brief-general [MISSPELLED?]
https://main--merative2--hlxsites.hlx.page/documents/brief/clinical-developement-solution-brief-general-old
https://main--merative2--hlxsites.hlx.page/documents/brief/clinical-development-solution-brief-general
https://main--merative2--hlxsites.hlx.page/documents/brief/clinical-development-solution-brief-medical-device
https://main--merative2--hlxsites.hlx.page/documents/brief/clinical-development-solution-brief-pharma
https://main--merative2--hlxsites.hlx.page/documents/brief/dynamed-and-micromedex-with-watson-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/flexible-analytics-for-providers-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/flexible-analytics-solution-brief-general
https://main--merative2--hlxsites.hlx.page/documents/brief/healthcare-analytics-software-for-advisors
https://main--merative2--hlxsites.hlx.page/documents/brief/health-insights-for-employers-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/health-insights-for-government
https://main--merative2--hlxsites.hlx.page/documents/brief/health-insights-for-health-plans-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/how-employers-can-guide-benefits-strategy
https://main--merative2--hlxsites.hlx.page/documents/brief/iconnect-enterprise-archive-data-sheet
https://main--merative2--hlxsites.hlx.page/documents/brief/imaging-ai-orchestrator-data-sheet-it
https://main--merative2--hlxsites.hlx.page/documents/brief/imaging-ai-orchestrator-data-sheet-provider
https://main--merative2--hlxsites.hlx.page/documents/brief/imaging-vision-brochure
https://main--merative2--hlxsites.hlx.page/documents/brief/marketscan-explainer-general
https://main--merative2--hlxsites.hlx.page/documents/brief/marketscan-research-databases-for-life-sciences-researchers
https://main--merative2--hlxsites.hlx.page/documents/brief/mcd-3077987612-merative-clinical-development-med-device-sb-v2
https://main--merative2--hlxsites.hlx.page/documents/brief/mcd-3078072014-merative-clinical-development-pharma
https://main--merative2--hlxsites.hlx.page/documents/brief/merative-phytel-automating-screening
https://main--merative2--hlxsites.hlx.page/documents/brief/merge-cardio-merge-hemo-brochure
https://main--merative2--hlxsites.hlx.page/documents/brief/merge-healthcare-symbols-glossary
https://main--merative2--hlxsites.hlx.page/documents/brief/merge-pacs-data-sheet
https://main--merative2--hlxsites.hlx.page/documents/brief/micromedex-with-watson-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/orbitalrx-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/phytel-outreach-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/price-transparency-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/price-transparency-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/real-world-evidence-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/rsna-merative-agenda
https://main--merative2--hlxsites.hlx.page/documents/brief/sa-spotlight-care-outcomes
https://main--merative2--hlxsites.hlx.page/documents/brief/smarter-health-and-human-services-solution-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/spotlight-integrated-care-outcomes
https://main--merative2--hlxsites.hlx.page/documents/brief/spotlight-on-outcomes
https://main--merative2--hlxsites.hlx.page/documents/brief/spotlight-on-outcomes-fi
https://main--merative2--hlxsites.hlx.page/documents/brief/treatment-cost-calculator-price-transparency-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/watson-care-manager-data-sheet
https://main--merative2--hlxsites.hlx.page/documents/brief/zelta-endpoint-adjudication-module-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/zelta-randomization-trial-supply-mgmt-module-brief
https://main--merative2--hlxsites.hlx.page/documents/brief/zelta-smart-report-module-brief

**Comment by helms-charity** [comment]
@sachinmesh ready for your review.

**Comment by keith-kaplan** [comment]
@venturewise I don't think Sachin has to review all these pages since it's all from a template and he's commented on the other issues for PDF viewer feedback.

I've gone through and cleaned up all of the PDF pages with adding correct metadata. THey are all in sharedpoint https://merative.sharepoint.com/sites/Merative.comWebsite/Shared%20Documents/Forms/AllItems.aspx?isAscending=false&id=%2Fsites%2FMerative%2EcomWebsite%2FShared%20Documents%2Fwebsite%2Fdocuments%2Fbrief&sortField=Modified&viewid=472996a8%2Df9ce%2D49f3%2Da65d%2Dfa8f62592c02

The list above is not accurate, but what is in Sharepoint has the latest.

**Comment by helms-charity** [comment]
Sounds good! I just wanted to be sure someone was looking at them.

**Comment by helms-charity** [comment]
@keith-kaplan you may want to have Scott review these for AssetTypes, I noticed some eyebrows missing as I was generally clicking around. I don't see that he edited any of the Brief pages in Sharepoint yet.

**Comment by keith-kaplan** [comment]
@venturewise thanks before we publish the pages we'll go through and ensure they are tagged properly.
