### ISSUE TITLE
QA: /documents/case-study pages

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#216]
These are all using the same template. They have been updated to use the request consult CTA fragment.

https://main--merative2--hlxsites.hlx.page/documents/case-study/4-ways-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/biorasi-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/biorasi-case-study-old
https://main--merative2--hlxsites.hlx.page/documents/case-study/boehringer-ingelheim-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/george-clinical-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/health-partners-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/loudoun-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/mms-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/new-york-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/ogden-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/personalizing-health-benefits-enrollment-liberty-mutual
https://main--merative2--hlxsites.hlx.page/documents/case-study/prosciento-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/prosciento-case-study-old
https://main--merative2--hlxsites.hlx.page/documents/case-study/protrial-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/protrial-case-study-old
https://main--merative2--hlxsites.hlx.page/documents/case-study/prudential-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/ricoh-partner-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/shoppable-services-with-treatment-cost-calculator
https://main--merative2--hlxsites.hlx.page/documents/case-study/sonoma-care-management-approach
https://main--merative2--hlxsites.hlx.page/documents/case-study/southern-star-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/the-ohio-state-university-health-plan-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/tidalhealth-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/uva-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/veristat-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/whirlpool-case-study

**Comment by helms-charity** [comment]
@sachinmesh ready for your review.

**Comment by sachinmesh** [comment]
1. CTA text shouldn't be underlined in any way. Rest the CTA specifications is all correct.
2. Padding in the leadspace should be 96px above and below.
3. Tag/Pills specifications are wrong 
![IMG-1404](https://user-images.githubusercontent.com/124026684/232386767-1ed9fe38-544e-4489-b34a-321dc9f76fdc.jpg)
4. Font style for the pills should be 16px Alliance no.1 regular.

CC: @anabarcelona

**Comment by helms-charity** [comment]
@sachinmesh, it is ready once again for your review.
- CTA underline removed
- leadspace padding for desktop increased to 96px
- tags style created for desktop 

Fixed on this pull request: https://github.com/hlxsites/merative2/pull/98

**Comment by sachinmesh** [comment]
CTA underline removed **- Fixed**
leadspace padding for desktop increased to 96px **- Fixed**
tags style created for desktop **- Fixed**

Just on hover the download text is disappearing.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/124026684/232682661-e901037d-9ce7-4a39-91d6-4a9d52b902b7.png">
CC: @anabarcelona

**Comment by keith-kaplan** [comment]
Having Scott help out with authoring edits for metadata. These are the ones to review....
https://main--merative2--hlxsites.hlx.page/documents/case-study/4-ways-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/biorasi-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/boehringer-ingelheim-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/george-clinical-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/health-partners-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/loudoun-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/mms-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/new-york-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/ogden-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/personalizing-health-benefits-enrollment-liberty-mutual
https://main--merative2--hlxsites.hlx.page/documents/case-study/prosciento-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/protrial-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/prudential-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/ricoh-partner-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/shoppable-services-with-treatment-cost-calculator
https://main--merative2--hlxsites.hlx.page/documents/case-study/sonoma-care-management-approach
https://main--merative2--hlxsites.hlx.page/documents/case-study/southern-star-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/the-ohio-state-university-health-plan-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/tidalhealth-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/uva-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/veristat-case-study
https://main--merative2--hlxsites.hlx.page/documents/case-study/whirlpool-case-study

**Comment by helms-charity** [comment]
@keith-kaplan will you or Scott be deleting the "old" or unneeded pages from Sharepoint?

**Comment by helms-charity** [comment]
> CTA underline removed **- Fixed** leadspace padding for desktop increased to 96px **- Fixed** tags style created for desktop **- Fixed**
> 
> Just on hover the download text is disappearing. <img alt="image" width="302" src="https://user-images.githubusercontent.com/124026684/232682661-e901037d-9ce7-4a39-91d6-4a9d52b902b7.png"> CC: @anabarcelona

@sachinmesh this button hover was fixed

**Comment by keith-kaplan** [comment]
> @keith-kaplan will you or Scott be deleting the "old" or unneeded pages from Sharepoint?

Yes, They should be removed already. I unpublished and deleted.

**Comment by keith-kaplan** [comment]
@venturewise  I think the one thing I'm not seeing on a lot of these PDF viewer pages is the Eyebrow on the related documents cards. Will that get updated when these are published?

**Comment by helms-charity** [comment]
@keith-kaplan I am looking into that now. Question though, you said hard coding the eyebrow to say "BLOG" for blog page cards was fine. ~~Do you want to make "CASE STUDY" cards add that eyebrow automatically as well? Or do you anticipate needing to change that?~~
Actually -- I just noticed "blog" is based on the template name. Since case studies use the "document" template and not a special "case study" template, there's nothing to hook on to, so we need the assetType anyway.

**Comment by keith-kaplan** [comment]
Yes, that's correct. I think pulling from AssetType is best option.

**Comment by helms-charity** [comment]
@keith-kaplan the eyebrows should be showing now, we had a typo in the javascript that was updated.

**Comment by scottbridgeman** [comment]
@keith-kaplan  - I've QA'ed the case-study pages/documents. The metadata is in good shape. We may want to look at headlines, descriptions and related documents. I've also deleted the "-old" documents as well as any that were for Phytel.

**Comment by helms-charity** [comment]
@keith-kaplan are we good to close this ticket?

**Comment by keith-kaplan** [comment]
@venturewise  yes, let's close it. I noted comments here 
![image](https://user-images.githubusercontent.com/111377779/234981445-a70209e5-3e55-4af1-b46b-34f10f07c4f9.png)

**Comment by helms-charity** [comment]
Ok, closing as the readtime is being addressed via https://github.com/hlxsites/merative/issues/217.
