### ISSUE TITLE
QA: /documents/ebook, /infographic, /white-paper

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#217]
These are all using the same template. They are using the request consult CTA fragment.

https://main--merative2--hlxsites.hlx.page/documents/ebook/child-welfare-forging-stronger-connections
https://main--merative2--hlxsites.hlx.page/documents/ebook/zelta-enablement-bundle-client-presentation

https://main--merative2--hlxsites.hlx.page/documents/infographic/2023-payer-trends-in-healthcare
https://main--merative2--hlxsites.hlx.page/documents/infographic/chso-infographic
https://main--merative2--hlxsites.hlx.page/documents/infographic/mcd-3936774507-zelta-ig

https://main--merative2--hlxsites.hlx.page/documents/white-paper/coordinated-health-and-social-outcomes
https://main--merative2--hlxsites.hlx.page/documents/white-paper/medical-episode-grouper-applications-and-methodology

**Comment by helms-charity** [comment]
@sachinmesh ready for your review.

**Comment by sachinmesh** [comment]
Text inside the CTA shouldn't be underlined.

**Comment by helms-charity** [comment]
I just also noticed that the Inline link style should only have 1px bottom underline, per:
 https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=272%3A62&t=6AEt8K8PTmecZmjo-1

Figma link for the tag styles:
https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=1245%3A10430&t=J9xmhxzxZDK54rzm-1

**Comment by helms-charity** [comment]
@sachinmesh the CTA underline was fixed, thanks for flagging, that was an accidental regression. Please review again?

Fixed via this pull request: https://github.com/hlxsites/merative2/pull/98

**Comment by keith-kaplan** [comment]
@venturewise I'm noticing in all of the related documents block they're missing the eyebrow. I think @amol-anand  said they were pulling from AssetType. I can go through the documents and ensure all the /document pages have those items in there.

**Comment by helms-charity** [comment]
Ok, @keith-kaplan I see that indeed there is a place for it in the HTML, but the div is empty.
You are right, I think is looking for "asset type" to be in the link's metadata table 
![image](https://user-images.githubusercontent.com/3883795/232548630-e4e57f1f-7c8d-4c21-b7cf-39e89d047be3.png)

**Comment by keith-kaplan** [comment]
Ok, great. So we just need to author those values on the documents then. I can start doing that today.

**Comment by helms-charity** [comment]
The blog template pages though will use the asset type as "BLOG" no matter what is in the metadata. Is that expected/ok?

**Comment by keith-kaplan** [comment]
Reviewed these docs and updated metadata. I still need to see the eyebrows from the asset type come in on the related documents block.



https://main--merative2--hlxsites.hlx.page/documents/ebook/child-welfare-forging-stronger-connections
https://main--merative2--hlxsites.hlx.page/documents/infographic/2023-payer-trends-in-healthcare
https://main--merative2--hlxsites.hlx.page/documents/infographic/chso-infographic
- Third resource card not coming through

https://main--merative2--hlxsites.hlx.page/documents/infographic/mcd-3936774507-zelta-ig (new URL is https://main--merative2--hlxsites.hlx.page/documents/infographic/zelta-clinical-trials-platform)

https://main--merative2--hlxsites.hlx.page/documents/white-paper/coordinated-health-and-social-outcomes
https://main--merative2--hlxsites.hlx.page/documents/white-paper/medical-episode-grouper-applications-and-methodology


Do not publish (PDF Viewer not needed, can delete page)
https://main--merative2--hlxsites.hlx.page/documents/ebook/zelta-enablement-bundle-client-presentation

**Comment by helms-charity** [comment]
@keith-kaplan This is ready for your re-review.

**Comment by keith-kaplan** [comment]
@venturewise  thanks. Just noticed this on all the PDF viewer pages. Looks like a misalignment of the tags on Desktop devices...

![image](https://user-images.githubusercontent.com/111377779/234979494-9c42c448-871f-4b88-9f0b-78167c79125c.png)

**Comment by helms-charity** [comment]
ok, I see it was changed today. I think we'll separate the .readtime margin onto it's own style and that should fix it. Will let you know when ready.
![image](https://user-images.githubusercontent.com/3883795/234982678-ae540546-dc6b-4835-b229-5b2cbb4abbe9.png)

**Comment by helms-charity** [comment]
@keith-kaplan this readtime was fixed, can you take another look?

**Comment by keith-kaplan** [comment]
Much better. Thank you.
