### ISSUE TITLE
Metadata inconsistencies under /documents

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#218]
Hi @keith-kaplan ,
As i was going through all the pages under /documents, I noticed a lot of differences in the amount of metadata. I just wanted to bring this to your attention so you could instruct authors as needed.

![image](https://user-images.githubusercontent.com/3883795/232045644-c478d103-6076-4028-a744-6d6893db4502.png)

**Comment by keith-kaplan** [comment]
@venturewise on every document page we should have the DocumentTags, AssetType, Page Type, orgFunction, Parent, Product Family values in the metadata.

As I got through the pages for the PDF Viewer I can add that info in.

**Comment by keith-kaplan** [comment]
We can mark this as done. I'd say for any content authoring guidance we can just reference a page that has all this info filled out already.
