### ISSUE TITLE
Convert special leadspace download link to global button

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#220]
The downloadLink constant should be updated to create a tertiary button instead of an A link so that we can apply the same global styling.

Before:
https://main--merative2--hlxsites.hlx.page/documents/brief/spotlight-integrated-care-outcomes
![image](https://user-images.githubusercontent.com/3883795/232065484-f5bee1ed-175f-44b3-b54f-0c0a26efc467.png)

After:
(see Media Resources section for example) https://main--merative2--hlxsites.hlx.page/newsroom
![image](https://user-images.githubusercontent.com/3883795/232065821-1c01e930-f85e-4012-8f82-9f048ce8994a.png)

And the download link in the leadspace should have the arrow with the underline icon: https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=9151%3A41451&t=J9xmhxzxZDK54rzm-1

**Comment by arumsey** [comment]
If the download link is being added programatically you'll need to do something similar to `related-resources` which calls `deorateButtons` and `decorateIcons` after the new Tertiary link button is added.

https://github.com/hlxsites/merative2/blob/main/blocks/related-resources/related-resources.js#L65
