### ISSUE TITLE
Related-resources defects with manually-authored cards

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#221]
1.
 related-resources section of https://main--merative2--hlxsites.hlx.page/newsroom, there's a non-arrow at the icon area of the last card, which is to www.ibm.com (and is considered to be an "internal" link I believe).

2.
The ellipsis "..." is on a separate line in the last 3 cards.
![image](https://user-images.githubusercontent.com/3883795/232073344-0704df81-e3a7-4dec-993b-6d80bd7ddf1f.png)

3. 
Keith asked for a manual override ability to link to have custom text when linking to internal pages. However, the cards are bringing in the info from the linked page's metadata regardless, so we should ask Keith if there needs to be another metadata line that's called 'eyebrow" which can be authored on each blog page, or if he's OK with having "BLOG" populated there?
![image](https://user-images.githubusercontent.com/3883795/232069680-7dc1b821-dc20-4d54-a31f-48cd5cc2a5fc.png)

**Comment by arumsey** [comment]
When hovering over a card the `title` should also include the full un-truncated text and not the truncated version.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1004204/232118807-3546f890-4d56-431a-bff9-84b80e779073.png">

**Comment by arumsey** [comment]
Consider using line clamp instead of # of chars.

```
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  line-clamp: 3;
```

**Comment by helms-charity** [comment]
I don't know if the vendor prefixes are necessary anymore, see https://caniuse.com/?search=line-clamp for example. But also let's go with line-clamp: 4, as I can see the current cards truncate at 160 characters right about there.

![image](https://user-images.githubusercontent.com/3883795/232141918-c75052d7-258f-404f-ae17-81a7cc3f24d8.png)

**Comment by helms-charity** [comment]
Update for item #3, the blog eyebrow can be left as is per Keith:
![image](https://user-images.githubusercontent.com/3883795/232589600-25463b81-899a-4c92-8741-764b19813d5f.png)
