### ISSUE TITLE
XXL inline links look broken

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#224]
Not sure where else we have this treatment, but the links that are in the body of this blog have font size inconsistencies.
https://main--merative2--hlxsites.hlx.page/blog/human-centered-design-solves-business-problems

Compare to the long links that are in the "References" / footnote area, those seem to be correctly formatted.

**Comment by helms-charity** [comment]
@keith-kaplan , there are a couple places on [pages such as this ](https://main--merative2--hlxsites.hlx.page/blog/human-centered-design-solves-business-problems )where a 1 sentence paragraph is linked, and I think a decision needs to be made on how to treat these in the design.

The link styles were changed around a month ago, [per this Figma page](https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=272%3A62&t=6AEt8K8PTmecZmjo-1) where there is 1 "button" type of standalone link style (bolder and a set font size), and an in-line link that appears in the middle of a sentence and blends in with the font style.

We have scripted the site so that  we are treating any link that is wrapped in `<p></p>` on its own as the "Standalone Link" style, and also adding an icon to the link based on the type. But, I think the links here were intended more as "In-line Links" (just like they do in the footnotes). If that's correct, then to fix the style, authors will have to leave some part of the sentence unlinked. 

So in this case, I'd not link the words "Read how the", and keep the rest of the sentenced linked.
![image](https://user-images.githubusercontent.com/3883795/232592699-20ec5bb6-094b-4331-bc61-35c0bd7cf10a.png)

What do you think?

**Comment by keith-kaplan** [comment]
I agree with your above statement. Short links like that should have the new inline style, but one of the things we've received feedback from the content team on is a some sort of design for a call to action within in the body of the blog. Something that breaks out the copy a bit. 

A simple solve for the above example is to link the text to a new /documents link with the PDF viewer. Another alternative fo this is to use the iConnect block, maybe without the icon.

Regardless, I think we need to get with our designers to come up with a new CTA block that could be used a call out in the body copy.

**Comment by helms-charity** [comment]
OK, @keith-kaplan, I have relinked and bolded those sentence links, I think this works in the interim?

![image](https://user-images.githubusercontent.com/3883795/232596919-51f4ac66-35fe-40ac-8e94-d64102f0ece9.png)

**Comment by keith-kaplan** [comment]
I agree. Thank you.
