### ISSUE TITLE
Link the entire card?

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#225]
Is there any reason not to link the entire card for related articles and related resources?
I think it is a better user experience

Example of cards that have this behavior: https://advisory.kpmg.us/ (under the hero space, see the 3 cards)

example of ours:
https://main--merative2--hlxsites.hlx.page/blog/where-do-you-start-when-tasked-with-delivering-social-security-benefits

**Comment by VladimirZaets** [comment]
@venturewise I agree, that it is a better user expirience
