### ISSUE TITLE
Paths to route to AEMCS from CDN

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#228]
All traffic should hit Franklin first except these paths below which would go to AEMCS.

The only conflict is /content/dam/merative/documents/* which should still be served from Franklin.

/crx*
/system*
/apps*
/bin/*
/etc*
/libs*
/content* (EXCEPT /content/dam/merative/documents/*)
/callback*
/screens*
/adobe*
/graphql*

**Comment by helms-charity** [comment]
@amol-anand @arumsey please let me shadow you in whatever you're doing with this, I need to learn.

**Comment by amol-anand** [comment]
stage.merative.com is now updated with the paths in addition to qa.
