### ISSUE TITLE
Changes to blog designs

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#23]
**Go with the design vs the actual site for design elements, but content on actual site is correct**

Need to adjust:
1. byline - only author, no title
2. hover state on current site is wrong. design is correct.
3. spacing issues
4. typography

**Comment by amol-anand** [comment]
In tablet mode: filter minimizes to the top. 
If filter is selected, then an only filter fly in from the left side shows up.

**Comment by amol-anand** [comment]
on scrolling down, filters become sticky from the top and have a drop shadow.
If you scroll the filter side panel, there is an Apply/Reset buttons at the bottom which are sticky at the bottom.

**Comment by amol-anand** [comment]
Read More at the end of the blog home should show how many articles are remaining. and load 6 at a time. First view is also featured article and 6 blogs based on latest date on top.

**Comment by kunwarsaluja** [comment]
We covered these in other issue specific stories. We can come back to any left after Content & Design QA
