### ISSUE TITLE
Always allow overrides on curated content

### ISSUE THREAD

**Issue by arumsey** [hlxsites/merative#230]
Blocks such as `teaser-list` and `related-resources` will noyl use overrieds for title, description and link title when the linked document has not been indexed. This logic needs to be flipped so that authored overrides for title,description and link title are used first if they exist and indexed values are only used as a fallback.

**Comment by VladimirZaets** [comment]
Hi, just want to clarify do I understand correct. 
You mean that firstly (with higher priority) we should take content from the related-resources block, as an example here:
"Focused innovation will deliver steady progress in health and social care" has header "Block" but in document its declated as "ARTICLE" (and same for description title, link title) 

Is that what you mean?

<img width="703" alt="Screen Shot 2023-04-19 at 1 11 52 PM" src="https://user-images.githubusercontent.com/8035672/233163688-13b55446-a53b-4ad0-8513-f529901047df.png">
<img width="1397" alt="Screen Shot 2023-04-19 at 1 11 45 PM" src="https://user-images.githubusercontent.com/8035672/233163695-32145945-8d4e-4e26-85da-fa5dbd52f7e3.png">

**Comment by arumsey** [comment]
@VladimirZaets Correct! Any content authored in the block (eyebrow, title, description, lint title) should have a higher priority than what comes from the index. Any of the index values should be used when an authored value is not available. This behaviour should be the same in `related-resources` and `teaser-list`.
