### ISSUE TITLE
MegaMenu: Check tab order

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#232]
Placeholder ticket to check accessibility when using keyboard for navigating.

**Comment by arumsey** [comment]
All menu items should be opened via mouse click, ENTER or SPACE bar with appropriate tabindex and aria values added.

https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls

**Comment by helms-charity** [comment]
@arumsey I have a feeling this was handled via the mega menu and Lighthouse tickets; feel free to close if this is a duplicate and no longer needed.
