### ISSUE TITLE
Color in back-to-top arrow?

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#233]
Question for @keith-kaplan 's team:

Since the back-to-top arrow is always on top, should we give it a fill color?

![image](https://user-images.githubusercontent.com/3883795/233620334-205bc92d-41b1-4bd0-b73e-94ff39bf7b28.png)

![image](https://user-images.githubusercontent.com/3883795/233620525-937b7d14-34e4-48ee-8f0f-02368d2aa1f6.png)

**Comment by keith-kaplan** [comment]
@venturewise, it should be on hover state with a fill color. Is that screenshot from a page on mobile? Can you send link.

**Comment by helms-charity** [comment]
It does fill in when you hover. ✔️ 
I was wondering if we should fill with white when it is NOT in a hover state so you don't see other content underneath as you scroll.

I noticed it on desktop, when the breakpoint is just over 1200px (eventually the arrow spreads out as the browser gets wider).
Example link: https://main--merative2--hlxsites.hlx.page/blog/employee-benefits-enrollments but you can see the same if you shrink your browser to 400px wide too.

**Comment by keith-kaplan** [comment]
@sachinmesh any comments on this?

**Comment by sachinmesh** [comment]
We can use a fill
<img width="712" alt="image" src="https://user-images.githubusercontent.com/124026684/233667419-ff5c0ae9-d0c9-4571-ad46-9a942b0732ef.png">

**Comment by helms-charity** [comment]
Addressed via https://github.com/hlxsites/merative2/pull/115 .
