### ISSUE TITLE
MegaMenu: Fonts and spacing

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#234]
Placeholder for any cosmetic fixes needed.
[See Figma file.](https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?node-id=496-6550&t=TNhYNN3XTWBeOOvH-0)

1. Fonts and logo sizes on the experience fragments:
![image](https://user-images.githubusercontent.com/3883795/233981075-b7a9bfbc-cab9-4bbf-b162-b9f64a45b831.png)

**Comment by sachinmesh** [comment]
**Test link Design QA** - https://144-mega-menu-content--merative2--hlxsites.hlx.page/



1. Product logo size is wrong
2. Spacing between the Explore CTA
3. What is merge? - Font style should be Alliance No.1 21px medium
4. Spacing below what is merge title and body text should be only 8px.
5. What is merge and the body text container should be of 336px wide and not 306px
6. The spacing of the cross icon from the what is merge container should be 12px
7. Top padding of the whole menu container from the nav should be 64px
8. Solution areas text and all the product categories below it should be aligned vertically
9. Spacing between solution areas and the first category should be 16px
10. The spacing between individual category container should be nil
11. The padding between the whole container, in case of health insights and the divider line should be 48px. right now it’s 73px.
<img width="500" alt="image" src="https://github.com/hlxsites/merative/assets/124026684/a3ca7abf-155b-4597-a6e6-e5dab03480d7">

12. There should be no divider line after the last explore product pages in each category like after the treatment cost calculator body text which is the last in this case.
      
<img width="358" alt="image" src="https://github.com/hlxsites/merative/assets/124026684/db58da10-e596-4897-98e5-dd0c37f95f00">


CC: @keith-kaplan @anabarcelona

**Comment by keith-kaplan** [comment]
@sachinmesh  it looks like testing should have been on the most updated branch. Can you please test on this URL - https://stage.merative.com/

**Comment by keith-kaplan** [comment]
@arumsey  it looks like some of items Sachin listed above are still present on the stage.merative.com instance. I think the product logo size looks correct, but the spacing issues are still present. I think numbers 2 thru 12 are still there. Can you take a look?

**Comment by keith-kaplan** [comment]
@arumsey  can you move this to Phase 2 label as well?

**Comment by helms-charity** [comment]
I changed it. I will start looking at this.

**Comment by arumsey** [comment]
All of the spacing issues have now been fixed.

<img width="1484" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/c2d0285b-dcfe-43b9-86cd-08690841a107">


- Product logo size is wrong **FIXED**
- Spacing between the Explore CTA **FIXED**
- What is merge? - Font style should be Alliance No.1 21px medium **FIXED**
- Spacing below what is merge title and body text should be only 8px. **FIXED**
- What is merge and the body text container should be of 336px wide and not 306px **FIXED**
- The spacing of the cross icon from the what is merge container should be 12px **FIXED**
- Top padding of the whole menu container from the nav should be 64px **FIXED**
- Solution areas text and all the product categories below it should be aligned vertically **FIXED**
- Spacing between solution areas and the first category should be 16px **FIXED**
- The spacing between individual category container should be nil **FIXED**
- The padding between the whole container, in case of health insights and the divider line should be 48px. right now it’s 73px. **FIXED**
- There should be no divider line after the last explore product pages in each category like after the treatment cost calculator body text which is the last in this case. **FIXED**

**Comment by arumsey** [comment]
<img width="1484" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/1e234185-cce9-48fa-9f4f-a2924bea9a65">

**Comment by keith-kaplan** [comment]
@sachinmesh  you can review here - https://234-megamenu-spacing--merative2--hlxsites.hlx.page

**Comment by arumsey** [comment]
@sachinmesh @keith-kaplan https://stage.merative.com/ has also been updated so you can continue testing there if you want.

**Comment by keith-kaplan** [comment]
Thanks @arumsey. This is looking good.

@sachinmesh @arumsey   a few comments I was discussing with Annmarie that were some blockers for go live. We want to make sure the navigation between Franklin and AEM are close as possible, so the visitor experience doesn't notice. Here's a video of the differences.

- The arrow-down icons used in each menu are larger than what is shown in AEM. Can we make those the same size?
<img width="210" alt="image" src="https://github.com/hlxsites/merative/assets/111377779/63d6c1a9-2346-4c86-919a-cf44fd2aee26">

- Here are some spacing items I'm noticing on Franklin
- Space on top of logo is 32px, space on bottom is 42px. On AEM space on top is 37 and on bottom it's 38
![image](https://github.com/hlxsites/merative/assets/111377779/0ecf9429-08ad-4efe-85e8-682e5ba3e6da)

-  Contact us button, space on top is 60, space on bottom is 23. On AEM space on top is 53 and space on bottom is 29 
![image](https://github.com/hlxsites/merative/assets/111377779/03aab2eb-5966-41dc-a44c-4a56b8331fdf)

- Spacing between logo and first menu item. Franklin is 125 and AEM is 96. 
![image](https://github.com/hlxsites/merative/assets/111377779/299d661f-3396-4bf2-8ea6-faa1925f55d3)

- spacing between last menu item and contact us button is  161 and AEM is 210
 
![image](https://github.com/hlxsites/merative/assets/111377779/c94f0d7c-231b-4b0f-bc25-0c87354c6940)




https://github.com/hlxsites/merative/assets/111377779/22157e21-5150-4775-880d-f0684dc6ee7e

**Comment by arumsey** [comment]
**Merative.com**
<img width="1440" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/1bbc3b4c-cf4f-4cf6-95b5-b70a45b3a0cb">

**Franklin**
<img width="1442" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/96be4a40-3560-43dd-b62e-e69c01b88ca6">

**Comment by arumsey** [comment]
**Merative.com**
<img width="770" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/35363aab-1116-4340-a227-7b20809b965f">

**Franklin**
![image](https://github.com/hlxsites/merative/assets/1004204/d0507227-de11-4be1-af35-db2047c78e95)
