### ISSUE TITLE
Font displaying incorrectly on page load

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#244]
@amol-anand @arumsey 

https://main--merative2--hlxsites.hlx.page/

It looks like another font is loading initially and then the correct fonts load. See video. Could it be this in the network?
![image](https://user-images.githubusercontent.com/111377779/235796292-79c90681-7151-44b1-8369-1c2b19d075ff.png)

https://user-images.githubusercontent.com/111377779/235796437-eaa05bdd-cef5-4aaa-b8e5-06eba9a47a1a.mp4

This is what the text is showing first
![2023-05-02_18-08-09](https://user-images.githubusercontent.com/111377779/235796448-f1259b70-f31e-46c4-a401-18eb04aecbee.png)

**Comment by arumsey** [comment]
@keith-kaplan How does this look https://244-font-loading--merative2--hlxsites.hlx.page/? Keep in mind caching on `.live` pages will reduce font-jitter further.
