### ISSUE TITLE
New Icons - AHIP

### ISSUE THREAD

**Issue by scottbridgeman** [hlxsites/merative#249]
Can we please add the following files to our icon library. 

![group-of-people](https://user-images.githubusercontent.com/108086144/236911059-0114160f-b421-4916-b7fa-bf2e2ff08760.svg)
![presentation-chart](https://user-images.githubusercontent.com/108086144/236911061-2e64c395-2ccf-41e3-9cf1-ad3506daf35e.svg)
![champagne](https://user-images.githubusercontent.com/108086144/236911112-e7647b03-c2be-45e1-812f-47367625225c.svg)

**Comment by keith-kaplan** [comment]
@arumsey is this a heavy lift? I assume the SVG icons need to be added to the code.

**Comment by arumsey** [comment]
@keith-kaplan Very easy. I will add them. I am also adding all the icons to the Sidekick library so they can easily be copy/pasted.

**Comment by scottbridgeman** [comment]
Thank you @arumsey! Love the idea of adding these to the library!

**Comment by arumsey** [comment]
@scottbridgeman Do you have preferred names for each of these icons?

**Comment by scottbridgeman** [comment]
@arumsey - Good question. I had been batting around ideas 

What is we go with: 

-- users-three (for the group of people)
-- champagne   (bubbly) 
-- presentation-chart   (bar graph on screen) 

Not sure if @keith-kaplan  has a POV here.

**Comment by arumsey** [comment]
Thanks @scottbridgeman I'll go with those names for now.
