### ISSUE TITLE
PDF Viewer Leadspace is right aligning text and missing read time and document tags

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#254]
Leadspace alignment of text should be to the left
Missing read time and document tags in leadspace

https://stage.merative.com/documents/case-study/protrial-case-study
https://main--merative2--hlxsites.hlx.page/documents/infographic/chso-infographic

![image](https://github.com/hlxsites/merative/assets/111377779/ec162f22-a2fb-430f-877b-9e7b2c3e8ac9)

**Comment by helms-charity** [comment]
This was fixed via https://github.com/hlxsites/merative2/pull/135.
