### ISSUE TITLE
Event page icons need aria-label

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/merative#257]
As seen here https://qa.merative.com/events/2023-zelta-user-conference, the Iinked In icons for the speakers don't have aria-labels and are being flagged by Lighthouse.

https://pagespeed.web.dev/analysis/https-qa-merative-com-events-2023-zelta-user-conference/jda6lfe558?form_factor=mobile

**Comment by arumsey** [comment]
Fixed in #234 

https://pagespeed.web.dev/analysis/https-234-megamenu-spacing--merative2--hlxsites-hlx-page-events-2023-zelta-user-conference/ph6ju4roc3?form_factor=desktop
