### ISSUE TITLE
Authoring Guide

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#34]
Create draft pages with all our blocks (including auto blocks) to show authors what content could look like and make it easy for them to copy into whatever they are working on.

**Comment by kunwarsaluja** [comment]
First Draft of the authoring guide : https://main--merative--hlxsites.hlx.page/drafts/authoring-guide

**Comment by amol-anand** [comment]
closing this for now. Will update the authoring guide during every phase of the project.
