### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/merative#39]
**how do current authors interact with the video component ?**
- the user clicks the video play button and it launches the video similar to how we have it on the homepage. We also have some videos that launch in vimeo.

**specific video formats to be allowed ?**
- Ideally we would allow multiple formats of video (MP4, WMV, AVI, etc.) but that's going to be dependent on what the brightcove tool allows

**are they hosted somewhere or can be from youtube/twitter etc.**
- Currently all videos are hosted on vimeo. It would be nice to have the option to link externally, but not necessary

**any modal that gets opened when someone clicks the play button or video plays once clicked in an embed iframe ?**
- would like a popup modal
- example of a link that opens in Vimeo- within the solutions section, click “See how it works” this launches the video: https://www.merative.com/health-plans

We didn’t have any videos in the blog posts because we didn’t have the capability to play them. At least that’s what Adobe Consulting Services said. We are looking into getting budget approval to onboard Brightcove.

**For the time being I think we can just a homepage video as an example or I know this page has a video as well** https://www.merative.com/clinical-decision-support

**Comment by amol-anand** [comment]
![Merative-Video](https://user-images.githubusercontent.com/7074782/213325204-39f4ed37-a862-4d28-baac-08f4f9081f7c.png)


Source: https://www.merative.com/healthcare-analytics

**Comment by arumsey** [comment]
> 

I am not seeing this example on their site anymore.

**Comment by arumsey** [comment]
https://github.com/hlxsites/merative2/pull/22
