### ISSUE TITLE
Update blog pages to add page metadata

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/merative#40]
Table Header: Metadata

| Metadata | |
| ------------- | ------------- |
| Template | Blog Article  |
| Featured Article  | false  |
| Author  | David Gruen, MD, MBA, FACR and Antonia Wells  |
| AuthorImage | [Blog Article](https://main--adobe-franklin-demo--amol-anand.hlx.page/media_186e54b87f1e5549899cd1b0dfb215eb219aaf704.png)  |
| Category  | Enterprise Imaging |
| Audience | Provider, Health Plans, Life Sciences  |
| Topic  | Healthcare Providers, Healthcare Technology |
| ReadTime | 6 min read |
| Description  | Trusted partnerships - built with consistency, meaningful interactions, and a shared vision - helped us earn 2021 KLAS recognition across our imaging portfolio.  |

@kunwarsaluja please add any other metadata that you depend on here so we capture it and update all the blog articles with it.

**Comment by amol-anand** [comment]
I updated topics/audiences and featured article in all the blog pages earlier this afternoon.

**Comment by amol-anand** [comment]
The descriptions are not correct for all the pages. The index is automatically pulling the author info because that's the first text in the blog article page. so we need to update the page metadata with the description instead for all blog pages. @kunwarsaluja

**Comment by kunwarsaluja** [comment]
@amol-anand  Do we need a new metadata property **_Description_** that would have 2 line content for the blog home ?

**Comment by amol-anand** [comment]
yes. I see you've already put that in. can we close this issue?
