### ISSUE TITLE
Bulleted List doesn't look formatted properly

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#63]
I don't think the format for the bulleted lists look right. We'll need to check with design to confirm they have the proper styling.

https://main--merative--hlxsites.hlx.page/blog/amol-test

<img width="966" alt="image" src="https://user-images.githubusercontent.com/111377779/208115102-df741f39-d5a8-42cd-9cc6-ba4e3869cd78.png">

**Comment by amol-anand** [comment]
There aren't any style for uls that we could find. threw in a margin-left of 25px for now to make it look better. let me know if this is ok or not. 

https://design-qa--merative--hlxsites.hlx.page/blog/amol-test

**Comment by keith-kaplan** [comment]
Alignment looks better, but on desktop it looks like font is larger than the rest.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/111377779/208251837-7e40def5-d267-4cdd-a7f9-054a1f2c8a3a.png">

can we also apply a similar margin for numbered lists as well? Look in references section.
<img width="888" alt="image" src="https://user-images.githubusercontent.com/111377779/208251867-90184d3d-1bb8-43d2-acc7-abc44fe122c4.png">

**Comment by amol-anand** [comment]
@keith-kaplan https://design-qa--merative--hlxsites.hlx.page/blog/amol-test fixed.
