### ISSUE TITLE
Logo is not a hyperlink to the homepage

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#64]
Can the logo be a hyperlink to the homepage?

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/111377779/208125923-cf8d31ec-7f91-4eac-83c2-61cffc409cb6.png">

**Comment by amol-anand** [comment]
Fixed in the design-qa branch. when that gets merged it will be fixed.

**Comment by amol-anand** [comment]
https://design-qa--merative--hlxsites.hlx.page/blog
