### ISSUE TITLE
Sachins Design QA

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/merative#66]
**Desktop: 1440** 

A. **Headspace** 
- Spacing above Merative blog title should be 96px, its 32px now. &check;
- Overall grid spacing – 156px from left and right needed, right now it's 149px. &check;
- Spacing left navigation and right featured article should be 48px, its 56px now.  ((**Pending**) KS: I see 48px as the column gap for (blog-content, Please cross-check and confirm)

B. **Left Navigation** 
- Extra Spacing of 16px above Clinical development support and categories. &check;
- Spacing after Social program management should be 48px, its 24px now. &check;
- Extra Spacing of 16px above Employer. &check;
- Extra 16px spacing above Real- World Evidence. &check;
- The color of the checkbox is blue; it should be neutral carbon. &check;
- The dimension of the checkbox is 16.5px, it should be 24px. &check;
- Spacing above showing results for should be 48px, right now it's 16px. &check;
- The spacing between the pills should be 8px, right now its 4px. &check;

C. **Featured Article** 
- Featured article image size should be 396x346px. &check;
- The spacing between the title and top edge of card should be 64px. &check;
- The spacing on left (with the image), right and bottom edge from the text should be 48px. &check;
- The spacing between Article title and body copy should be 8px, right now its 16px. &check;
- The spacing between body copy and authors name should be 48px. &check;

D. **Blog Cards** 
- Article image size should be 396x264px. &check;
- The spacing between the title and top and all edges of card should be 32px. &check;
- The spacing on left (with the image), right and bottom edge from the text should be 32px. &check;
- The spacing between Article title and body copy should be 8px, right now its 16px. &check;
- The spacing between body copy and authors name should be 24px. &check;
- Shadow on hover state of card is wrong.  &check;
- Wrong load more CTA is used (Dimensions are wrong). &check;
- The spacing below the CTA should be 160px. &check;

More Details [here](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/Shared%20Documents/website/drafts/Blog%20Franklin%20Design%20QA%20v1.docx?d=w7d73ed4ba6eb439297d858513359007d&csf=1&web=1&e=emtSzQ)

**Comment by amol-anand** [comment]
Wrapped up remaining issues after Kunwar finished most of them.

One caveat regarding: - Featured article image size should be 396x346px.

Since featured article can have text next to the image, the image cannot have a fixed height. it should still look good no matter what text is on the right (even if it is less / more than the image)

So I have set the min-height to the right values from the Figma file, set height: 100% (to cover the height in case text is long) and set object-fit:cover to ensure it doesn't look stretched when expanded.
