### ISSUE TITLE
Sachin's Design QA - Tablet

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/merative#68]
**Tablet: 768** 

- Top navigation bar – Padding on left and right is wrong. It’s 96 right now, should be 36. 
- Merative logo size is different.  
- Extra space of 32px is added above the title merative blog. It should be 64 only. 
- The title of the merative blog and bodycopy is on sand background. 
- The spacing between the bodycopy and the edge of the sand background is 48px. 
- From the sand background the filters have spacing of 32px. 
- The spacing between the filters and the feature article should be 32px. 
- Article image size should be 336x294. 
- The spacing between the bodycopy and the author in the feature article should be 48px. 
- The title font of feature article should be 18px Alliance no.1 light. 
- The author font should also be Alliance no.1 light 12 px. 

- Extra padding of 16px is seen on left side. The padding should 36px from both sides. 
- The spacing between the card article title and its bodycopy should be 8px. It’s 16px now. 
- The space between bodycopy and the author's name should be 24px. 
- The author font should be Alliance no.1 light not regular. 
- The spacing below the CTA should be 64px and not 160px. 

- Filter font should be Mobile/heading/h4 - 18px medium and not light. 
- Padding of the entire filter from left should be 36px and not 16px. 
- The cross icon should be of 20px size. 
- The cross icon spacing from the right should be 24px. 
- The spacing between filter text and Merative blog container should be 32px and then an 8px space is added above merative blog text. 
- The spacing below merative blog text and divider rule should be 24px. 
- The spacing above categories (and divider rule) should be 16px and below should be 24px. 
- The spacing between all the categories should be 16px. 
- Same follows as above (Point 7 and 8) for the audience and topic categories.  

**Tablet: Article 768** 

- Top nav merative logo and hamburger padding is incorrect. 
- Breadcrumb padding on left is wrong. It should be 36px as our grid padding. 
- The article hierarchy is wrong. 
- After breadcrumb Article title should come > Tags > Article image > Author name > Share links > Reading progress. 
- Article image size should be 696x468. 
- No padding seen on right hand side. 

- Spacing above related article should be 64px. 
- Spacing below related article should be 48px. 
- The color of card should be white. 
- The image size inside the card should be 336x224. 
- The spacing of title and bodycopy inside the card should be 8px. 
- The spacing from bodycopy to author name should be 24px. 
- Authour font should be light. 

- Leadgen grid is wrong. 
- Ready for consultation font should be Mobile/heading/h2 32px sorce serif pro light. 
- Bodycopy should be 16px alliance no.1 light  
- Spacing from bodycopy to CTA should be 32px.

**Comment by amol-anand** [comment]
Closing this as we have a new issue https://github.com/hlxsites/merative/issues/107 with the updated list.
