### ISSUE TITLE
Sachin Design QA Mobile

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/merative#78]
**Mobile: 375**  
- Grid on mobile is wrong. 24px padding should be on bpth sides. 
- Content is overlapping over the grid on right. 
- The spacing above and below of authors name should be 32px. 
- Space above related article text should be 64px and below it should be 48px. 
- Cards background shound be white.  
- The spacing between Title and bodycopy should be 8px. 
- The spacing between the bodycopy and the author's name should be 24px. 
- Ready for consultation font should be 32px source serif pro light.  
- Bodycopy font should be 16px Alliance no.1 light. 
- The spacing between title and bodycopy should be 16px. 
- Spacing above CTA should be 32px. 

New bugs per Sachin when looking at https://main--merative--hlxsites.hlx.page/blog  (Hope this is the right link.)
- Merative logo getting cut from the top.  &check; (dont see this happening anymore)
- Cards in related article should have a white bg. Right now only on hover state it shows a white bg.  &check; 
- Huge vertical side rainbow bar is seen  &check; (dont see this happening anymore)
- Top nav bar is missing on tablet and mobile. &check; (dont see this happening anymore)
- Extra padding on right on mobile. 24px padding should be on both sides on mobile.  &check; 
- The spacing on both left and right side should be 24px inside the card for text. &check;
- The spacing between title and bodycopy should be 8px. &check;
- The spacing between bodycopy and author’s name should be 24px. &check;
- The authors font should be 12px Alliance no.1 light &check;
- The spacing below the load more CTA should be 64px. &check;

**Comment by amol-anand** [comment]
Closing this as we have a new issue https://github.com/hlxsites/merative/issues/107 with the updated list.
